module Imagekit
  module Resources
    class Folders
      class Job
        def get: (
          String job_id,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Folders::JobGetResponse

        def initialize: (client: Imagekit::Client) -> void
      end
    end
  end
end
