# typed: strong

module Imagekitio
  module Models
    class NamedTransformation < Imagekitio::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(Imagekitio::NamedTransformation, Imagekitio::Internal::AnyHash)
        end

      # Unique identifier of the named transformation. This is generated by ImageKit
      # when you create a new named transformation.
      sig { returns(T.nilable(String)) }
      attr_reader :id

      sig { params(id: String).void }
      attr_writer :id

      # Timestamp when the named transformation was created.
      sig { returns(T.nilable(Time)) }
      attr_reader :created_at

      sig { params(created_at: Time).void }
      attr_writer :created_at

      # Whether this named transformation is currently disabled.
      sig { returns(T.nilable(T::Boolean)) }
      attr_reader :disabled

      sig { params(disabled: T::Boolean).void }
      attr_writer :disabled

      # Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
      sig { returns(T.nilable(String)) }
      attr_reader :name

      sig { params(name: String).void }
      attr_writer :name

      # The transformation string this name refers to.
      sig { returns(T.nilable(String)) }
      attr_reader :transformation

      sig { params(transformation: String).void }
      attr_writer :transformation

      # A named transformation is an alias for an actual transformation string, allowing
      # you to apply and later update complex transformations without changing your
      # image or video URLs. Learn more about
      # [named transformations](https://imagekit.io/docs/transformations#named-transformations).
      sig do
        params(
          id: String,
          created_at: Time,
          disabled: T::Boolean,
          name: String,
          transformation: String
        ).returns(T.attached_class)
      end
      def self.new(
        # Unique identifier of the named transformation. This is generated by ImageKit
        # when you create a new named transformation.
        id: nil,
        # Timestamp when the named transformation was created.
        created_at: nil,
        # Whether this named transformation is currently disabled.
        disabled: nil,
        # Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
        name: nil,
        # The transformation string this name refers to.
        transformation: nil
      )
      end

      sig do
        override.returns(
          {
            id: String,
            created_at: Time,
            disabled: T::Boolean,
            name: String,
            transformation: String
          }
        )
      end
      def to_hash
      end
    end
  end
end
