module Imagekit
  module Models
    module Files
      type bulk_remove_ai_tags_params =
        { ai_tags: ::Array[String], file_ids: ::Array[String] }
        & Imagekit::Internal::Type::request_parameters

      class BulkRemoveAITagsParams < Imagekit::Internal::Type::BaseModel
        extend Imagekit::Internal::Type::RequestParameters::Converter
        include Imagekit::Internal::Type::RequestParameters

        attr_accessor ai_tags: ::Array[String]

        attr_accessor file_ids: ::Array[String]

        def initialize: (
          ai_tags: ::Array[String],
          file_ids: ::Array[String],
          ?request_options: Imagekit::request_opts
        ) -> void

        def to_hash: -> {
          ai_tags: ::Array[String],
          file_ids: ::Array[String],
          request_options: Imagekit::RequestOptions
        }
      end
    end
  end
end
