module Imagekit
  module Models
    module Files
      type metadata_get_from_url_response =
        {
          audio_codec: String,
          bit_rate: Integer,
          density: Integer,
          duration: Integer,
          exif: Imagekit::Models::Files::MetadataGetFromURLResponse::Exif,
          format_: String,
          has_color_profile: bool,
          has_transparency: bool,
          height: Integer,
          p_hash: String,
          quality: Integer,
          size: Integer,
          video_codec: String,
          width: Integer
        }

      class MetadataGetFromURLResponse < Imagekit::Internal::Type::BaseModel
        attr_reader audio_codec: String?

        def audio_codec=: (String) -> String

        attr_reader bit_rate: Integer?

        def bit_rate=: (Integer) -> Integer

        attr_reader density: Integer?

        def density=: (Integer) -> Integer

        attr_reader duration: Integer?

        def duration=: (Integer) -> Integer

        attr_reader exif: Imagekit::Models::Files::MetadataGetFromURLResponse::Exif?

        def exif=: (
          Imagekit::Models::Files::MetadataGetFromURLResponse::Exif
        ) -> Imagekit::Models::Files::MetadataGetFromURLResponse::Exif

        attr_reader format_: String?

        def format_=: (String) -> String

        attr_reader has_color_profile: bool?

        def has_color_profile=: (bool) -> bool

        attr_reader has_transparency: bool?

        def has_transparency=: (bool) -> bool

        attr_reader height: Integer?

        def height=: (Integer) -> Integer

        attr_reader p_hash: String?

        def p_hash=: (String) -> String

        attr_reader quality: Integer?

        def quality=: (Integer) -> Integer

        attr_reader size: Integer?

        def size=: (Integer) -> Integer

        attr_reader video_codec: String?

        def video_codec=: (String) -> String

        attr_reader width: Integer?

        def width=: (Integer) -> Integer

        def initialize: (
          ?audio_codec: String,
          ?bit_rate: Integer,
          ?density: Integer,
          ?duration: Integer,
          ?exif: Imagekit::Models::Files::MetadataGetFromURLResponse::Exif,
          ?format_: String,
          ?has_color_profile: bool,
          ?has_transparency: bool,
          ?height: Integer,
          ?p_hash: String,
          ?quality: Integer,
          ?size: Integer,
          ?video_codec: String,
          ?width: Integer
        ) -> void

        def to_hash: -> {
          audio_codec: String,
          bit_rate: Integer,
          density: Integer,
          duration: Integer,
          exif: Imagekit::Models::Files::MetadataGetFromURLResponse::Exif,
          format_: String,
          has_color_profile: bool,
          has_transparency: bool,
          height: Integer,
          p_hash: String,
          quality: Integer,
          size: Integer,
          video_codec: String,
          width: Integer
        }

        type exif =
          {
            exif: Imagekit::ExifDetails,
            gps: Imagekit::Gps,
            image: Imagekit::ExifImage,
            interoperability: Imagekit::Interoperability,
            makernote: ::Hash[Symbol, top],
            thumbnail: Imagekit::Thumbnail
          }

        class Exif < Imagekit::Internal::Type::BaseModel
          attr_reader exif: Imagekit::ExifDetails?

          def exif=: (Imagekit::ExifDetails) -> Imagekit::ExifDetails

          attr_reader gps: Imagekit::Gps?

          def gps=: (Imagekit::Gps) -> Imagekit::Gps

          attr_reader image: Imagekit::ExifImage?

          def image=: (Imagekit::ExifImage) -> Imagekit::ExifImage

          attr_reader interoperability: Imagekit::Interoperability?

          def interoperability=: (
            Imagekit::Interoperability
          ) -> Imagekit::Interoperability

          attr_reader makernote: ::Hash[Symbol, top]?

          def makernote=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader thumbnail: Imagekit::Thumbnail?

          def thumbnail=: (Imagekit::Thumbnail) -> Imagekit::Thumbnail

          def initialize: (
            ?exif: Imagekit::ExifDetails,
            ?gps: Imagekit::Gps,
            ?image: Imagekit::ExifImage,
            ?interoperability: Imagekit::Interoperability,
            ?makernote: ::Hash[Symbol, top],
            ?thumbnail: Imagekit::Thumbnail
          ) -> void

          def to_hash: -> {
            exif: Imagekit::ExifDetails,
            gps: Imagekit::Gps,
            image: Imagekit::ExifImage,
            interoperability: Imagekit::Interoperability,
            makernote: ::Hash[Symbol, top],
            thumbnail: Imagekit::Thumbnail
          }
        end
      end
    end
  end
end
