module Imagekit
  module Models
    module Files
      type purge_status_response =
        { status: Imagekit::Models::Files::PurgeStatusResponse::status }

      class PurgeStatusResponse < Imagekit::Internal::Type::BaseModel
        attr_reader status: Imagekit::Models::Files::PurgeStatusResponse::status?

        def status=: (
          Imagekit::Models::Files::PurgeStatusResponse::status
        ) -> Imagekit::Models::Files::PurgeStatusResponse::status

        def initialize: (
          ?status: Imagekit::Models::Files::PurgeStatusResponse::status
        ) -> void

        def to_hash: -> {
          status: Imagekit::Models::Files::PurgeStatusResponse::status
        }

        type status = :Pending | :Completed

        module Status
          extend Imagekit::Internal::Type::Enum

          PENDING: :Pending
          COMPLETED: :Completed

          def self?.values: -> ::Array[Imagekit::Models::Files::PurgeStatusResponse::status]
        end
      end
    end
  end
end
