module Imagekit
  module Models
    module Files
      type purge_execute_response = { request_id: String }

      class PurgeExecuteResponse < Imagekit::Internal::Type::BaseModel
        attr_reader request_id: String?

        def request_id=: (String) -> String

        def initialize: (?request_id: String) -> void

        def to_hash: -> { request_id: String }
      end
    end
  end
end
