module Imagekit
  module Models
    module Files
      type version_delete_response = {  }

      class VersionDeleteResponse < Imagekit::Internal::Type::BaseModel
        def initialize: -> void

        def to_hash: -> {  }
      end
    end
  end
end
