module Imagekitio
  module Models
    type dam_file_version_create_event =
      { created_at: Time, data: top, type: :"file-version.created" }

    class DamFileVersionCreateEvent < Imagekitio::Models::BaseWebhookEvent
      def created_at: -> Time

      def created_at=: (Time _) -> Time

      def data: -> top

      def data=: (top _) -> top

      def `type`: -> :"file-version.created"

      def type=: (:"file-version.created" _) -> :"file-version.created"

      def initialize: (
        created_at: Time,
        data: top,
        ?type: :"file-version.created"
      ) -> void

      def to_hash: -> {
        created_at: Time,
        data: top,
        type: :"file-version.created"
      }
    end
  end
end
