module Imagekitio
  module Models
    type file =
      {
        ai_tags: ::Array[Imagekitio::File::AITag]?,
        audio_codec: String,
        bit_rate: Integer,
        created_at: Time,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        duration: Integer,
        embedded_metadata: ::Hash[Symbol, top],
        file_id: String,
        file_path: String,
        file_type: String,
        has_alpha: bool,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        mime: String,
        name: String,
        selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema],
        size: Float,
        tags: ::Array[String]?,
        thumbnail: String,
        type: Imagekitio::Models::File::type_,
        updated_at: Time,
        url: String,
        version_info: Imagekitio::File::VersionInfo,
        video_codec: String,
        width: Float
      }

    class File < Imagekitio::Internal::Type::BaseModel
      attr_accessor ai_tags: ::Array[Imagekitio::File::AITag]?

      attr_reader audio_codec: String?

      def audio_codec=: (String) -> String

      attr_reader bit_rate: Integer?

      def bit_rate=: (Integer) -> Integer

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_accessor custom_coordinates: String?

      attr_reader custom_metadata: ::Hash[Symbol, top]?

      def custom_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader duration: Integer?

      def duration=: (Integer) -> Integer

      attr_reader embedded_metadata: ::Hash[Symbol, top]?

      def embedded_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader file_id: String?

      def file_id=: (String) -> String

      attr_reader file_path: String?

      def file_path=: (String) -> String

      attr_reader file_type: String?

      def file_type=: (String) -> String

      attr_reader has_alpha: bool?

      def has_alpha=: (bool) -> bool

      attr_reader height: Float?

      def height=: (Float) -> Float

      attr_reader is_private_file: bool?

      def is_private_file=: (bool) -> bool

      attr_reader is_published: bool?

      def is_published=: (bool) -> bool

      attr_reader mime: String?

      def mime=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema]?

      def selected_fields_schema=: (
        ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema]
      ) -> ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema]

      attr_reader size: Float?

      def size=: (Float) -> Float

      attr_accessor tags: ::Array[String]?

      attr_reader thumbnail: String?

      def thumbnail=: (String) -> String

      attr_reader type: Imagekitio::Models::File::type_?

      def type=: (
        Imagekitio::Models::File::type_
      ) -> Imagekitio::Models::File::type_

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      attr_reader url: String?

      def url=: (String) -> String

      attr_reader version_info: Imagekitio::File::VersionInfo?

      def version_info=: (
        Imagekitio::File::VersionInfo
      ) -> Imagekitio::File::VersionInfo

      attr_reader video_codec: String?

      def video_codec=: (String) -> String

      attr_reader width: Float?

      def width=: (Float) -> Float

      def initialize: (
        ?ai_tags: ::Array[Imagekitio::File::AITag]?,
        ?audio_codec: String,
        ?bit_rate: Integer,
        ?created_at: Time,
        ?custom_coordinates: String?,
        ?custom_metadata: ::Hash[Symbol, top],
        ?description: String,
        ?duration: Integer,
        ?embedded_metadata: ::Hash[Symbol, top],
        ?file_id: String,
        ?file_path: String,
        ?file_type: String,
        ?has_alpha: bool,
        ?height: Float,
        ?is_private_file: bool,
        ?is_published: bool,
        ?mime: String,
        ?name: String,
        ?selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema],
        ?size: Float,
        ?tags: ::Array[String]?,
        ?thumbnail: String,
        ?type: Imagekitio::Models::File::type_,
        ?updated_at: Time,
        ?url: String,
        ?version_info: Imagekitio::File::VersionInfo,
        ?video_codec: String,
        ?width: Float
      ) -> void

      def to_hash: -> {
        ai_tags: ::Array[Imagekitio::File::AITag]?,
        audio_codec: String,
        bit_rate: Integer,
        created_at: Time,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        duration: Integer,
        embedded_metadata: ::Hash[Symbol, top],
        file_id: String,
        file_path: String,
        file_type: String,
        has_alpha: bool,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        mime: String,
        name: String,
        selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema],
        size: Float,
        tags: ::Array[String]?,
        thumbnail: String,
        type: Imagekitio::Models::File::type_,
        updated_at: Time,
        url: String,
        version_info: Imagekitio::File::VersionInfo,
        video_codec: String,
        width: Float
      }

      type type_ = :file | :"file-version"

      module Type
        extend Imagekitio::Internal::Type::Enum

        FILE: :file
        FILE_VERSION: :"file-version"

        def self?.values: -> ::Array[Imagekitio::Models::File::type_]
      end
    end
  end
end
