module Imagekitio
  module Models
    type file_copy_response = {  }

    class FileCopyResponse < Imagekitio::Internal::Type::BaseModel
      def initialize: -> void

      def to_hash: -> {  }
    end
  end
end
