module Imagekitio
  module Models
    type file_rename_response = { purge_request_id: String }

    class FileRenameResponse < Imagekitio::Internal::Type::BaseModel
      attr_reader purge_request_id: String?

      def purge_request_id=: (String) -> String

      def initialize: (?purge_request_id: String) -> void

      def to_hash: -> { purge_request_id: String }
    end
  end
end
