module Imagekitio
  module Models
    type file_upload_params =
      {
        file: Imagekitio::Internal::file_input,
        file_name: String,
        token: String,
        checks: String,
        custom_coordinates: String,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        expire: Integer,
        extensions: Imagekitio::Models::extensions,
        folder: String,
        is_private_file: bool,
        is_published: bool,
        overwrite_ai_tags: bool,
        overwrite_custom_metadata: bool,
        overwrite_file: bool,
        overwrite_tags: bool,
        public_key: String,
        response_fields: ::Array[Imagekitio::Models::FileUploadParams::response_field],
        signature: String,
        tags: ::Array[String],
        transformation: Imagekitio::FileUploadParams::Transformation,
        use_unique_file_name: bool,
        webhook_url: String
      }
      & Imagekitio::Internal::Type::request_parameters

    class FileUploadParams < Imagekitio::Internal::Type::BaseModel
      extend Imagekitio::Internal::Type::RequestParameters::Converter
      include Imagekitio::Internal::Type::RequestParameters

      attr_accessor file: Imagekitio::Internal::file_input

      attr_accessor file_name: String

      attr_reader token: String?

      def token=: (String) -> String

      attr_reader checks: String?

      def checks=: (String) -> String

      attr_reader custom_coordinates: String?

      def custom_coordinates=: (String) -> String

      attr_reader custom_metadata: ::Hash[Symbol, top]?

      def custom_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader expire: Integer?

      def expire=: (Integer) -> Integer

      attr_reader extensions: Imagekitio::Models::extensions?

      def extensions=: (
        Imagekitio::Models::extensions
      ) -> Imagekitio::Models::extensions

      attr_reader folder: String?

      def folder=: (String) -> String

      attr_reader is_private_file: bool?

      def is_private_file=: (bool) -> bool

      attr_reader is_published: bool?

      def is_published=: (bool) -> bool

      attr_reader overwrite_ai_tags: bool?

      def overwrite_ai_tags=: (bool) -> bool

      attr_reader overwrite_custom_metadata: bool?

      def overwrite_custom_metadata=: (bool) -> bool

      attr_reader overwrite_file: bool?

      def overwrite_file=: (bool) -> bool

      attr_reader overwrite_tags: bool?

      def overwrite_tags=: (bool) -> bool

      attr_reader public_key: String?

      def public_key=: (String) -> String

      attr_reader response_fields: ::Array[Imagekitio::Models::FileUploadParams::response_field]?

      def response_fields=: (
        ::Array[Imagekitio::Models::FileUploadParams::response_field]
      ) -> ::Array[Imagekitio::Models::FileUploadParams::response_field]

      attr_reader signature: String?

      def signature=: (String) -> String

      attr_reader tags: ::Array[String]?

      def tags=: (::Array[String]) -> ::Array[String]

      attr_reader transformation: Imagekitio::FileUploadParams::Transformation?

      def transformation=: (
        Imagekitio::FileUploadParams::Transformation
      ) -> Imagekitio::FileUploadParams::Transformation

      attr_reader use_unique_file_name: bool?

      def use_unique_file_name=: (bool) -> bool

      attr_reader webhook_url: String?

      def webhook_url=: (String) -> String

      def initialize: (
        file: Imagekitio::Internal::file_input,
        file_name: String,
        ?token: String,
        ?checks: String,
        ?custom_coordinates: String,
        ?custom_metadata: ::Hash[Symbol, top],
        ?description: String,
        ?expire: Integer,
        ?extensions: Imagekitio::Models::extensions,
        ?folder: String,
        ?is_private_file: bool,
        ?is_published: bool,
        ?overwrite_ai_tags: bool,
        ?overwrite_custom_metadata: bool,
        ?overwrite_file: bool,
        ?overwrite_tags: bool,
        ?public_key: String,
        ?response_fields: ::Array[Imagekitio::Models::FileUploadParams::response_field],
        ?signature: String,
        ?tags: ::Array[String],
        ?transformation: Imagekitio::FileUploadParams::Transformation,
        ?use_unique_file_name: bool,
        ?webhook_url: String,
        ?request_options: Imagekitio::request_opts
      ) -> void

      def to_hash: -> {
        file: Imagekitio::Internal::file_input,
        file_name: String,
        token: String,
        checks: String,
        custom_coordinates: String,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        expire: Integer,
        extensions: Imagekitio::Models::extensions,
        folder: String,
        is_private_file: bool,
        is_published: bool,
        overwrite_ai_tags: bool,
        overwrite_custom_metadata: bool,
        overwrite_file: bool,
        overwrite_tags: bool,
        public_key: String,
        response_fields: ::Array[Imagekitio::Models::FileUploadParams::response_field],
        signature: String,
        tags: ::Array[String],
        transformation: Imagekitio::FileUploadParams::Transformation,
        use_unique_file_name: bool,
        webhook_url: String,
        request_options: Imagekitio::RequestOptions
      }

      type response_field =
        :tags
        | :customCoordinates
        | :isPrivateFile
        | :embeddedMetadata
        | :isPublished
        | :customMetadata
        | :metadata
        | :selectedFieldsSchema

      module ResponseField
        extend Imagekitio::Internal::Type::Enum

        TAGS: :tags
        CUSTOM_COORDINATES: :customCoordinates
        IS_PRIVATE_FILE: :isPrivateFile
        EMBEDDED_METADATA: :embeddedMetadata
        IS_PUBLISHED: :isPublished
        CUSTOM_METADATA: :customMetadata
        METADATA: :metadata
        SELECTED_FIELDS_SCHEMA: :selectedFieldsSchema

        def self?.values: -> ::Array[Imagekitio::Models::FileUploadParams::response_field]
      end

      type transformation =
        {
          post: ::Array[Imagekitio::Models::FileUploadParams::Transformation::post],
          pre: String
        }

      class Transformation < Imagekitio::Internal::Type::BaseModel
        attr_reader post: ::Array[Imagekitio::Models::FileUploadParams::Transformation::post]?

        def post=: (
          ::Array[Imagekitio::Models::FileUploadParams::Transformation::post]
        ) -> ::Array[Imagekitio::Models::FileUploadParams::Transformation::post]

        attr_reader pre: String?

        def pre=: (String) -> String

        def initialize: (
          ?post: ::Array[Imagekitio::Models::FileUploadParams::Transformation::post],
          ?pre: String
        ) -> void

        def to_hash: -> {
          post: ::Array[Imagekitio::Models::FileUploadParams::Transformation::post],
          pre: String
        }

        type post =
          Imagekitio::FileUploadParams::Transformation::Post::Transformation
          | Imagekitio::FileUploadParams::Transformation::Post::GifToVideo
          | Imagekitio::FileUploadParams::Transformation::Post::Thumbnail
          | Imagekitio::FileUploadParams::Transformation::Post::Abs

        module Post
          extend Imagekitio::Internal::Type::Union

          type transformation = { type: :transformation, value: String }

          class Transformation < Imagekitio::Internal::Type::BaseModel
            attr_accessor type: :transformation

            attr_accessor value: String

            def initialize: (value: String, ?type: :transformation) -> void

            def to_hash: -> { type: :transformation, value: String }
          end

          type gif_to_video = { type: :"gif-to-video", value: String }

          class GifToVideo < Imagekitio::Internal::Type::BaseModel
            attr_accessor type: :"gif-to-video"

            attr_reader value: String?

            def value=: (String) -> String

            def initialize: (?value: String, ?type: :"gif-to-video") -> void

            def to_hash: -> { type: :"gif-to-video", value: String }
          end

          type thumbnail = { type: :thumbnail, value: String }

          class Thumbnail < Imagekitio::Internal::Type::BaseModel
            attr_accessor type: :thumbnail

            attr_reader value: String?

            def value=: (String) -> String

            def initialize: (?value: String, ?type: :thumbnail) -> void

            def to_hash: -> { type: :thumbnail, value: String }
          end

          type abs =
            {
              protocol: Imagekitio::Models::FileUploadParams::Transformation::Post::Abs::protocol,
              type: :abs,
              value: String
            }

          class Abs < Imagekitio::Internal::Type::BaseModel
            attr_accessor protocol: Imagekitio::Models::FileUploadParams::Transformation::Post::Abs::protocol

            attr_accessor type: :abs

            attr_accessor value: String

            def initialize: (
              protocol: Imagekitio::Models::FileUploadParams::Transformation::Post::Abs::protocol,
              value: String,
              ?type: :abs
            ) -> void

            def to_hash: -> {
              protocol: Imagekitio::Models::FileUploadParams::Transformation::Post::Abs::protocol,
              type: :abs,
              value: String
            }

            type protocol = :hls | :dash

            module Protocol
              extend Imagekitio::Internal::Type::Enum

              HLS: :hls
              DASH: :dash

              def self?.values: -> ::Array[Imagekitio::Models::FileUploadParams::Transformation::Post::Abs::protocol]
            end
          end

          def self?.variants: -> ::Array[Imagekitio::Models::FileUploadParams::Transformation::post]
        end
      end
    end
  end
end
