module Imagekitio
  module Models
    type file_deleted_webhook_event =
      {
        created_at: Time,
        data: Imagekitio::FileDeletedWebhookEvent::Data,
        type: :"file.deleted"
      }

    class FileDeletedWebhookEvent < Imagekitio::Models::BaseWebhookEvent
      def created_at: -> Time

      def created_at=: (Time _) -> Time

      def data: -> Imagekitio::FileDeletedWebhookEvent::Data

      def data=: (
        Imagekitio::FileDeletedWebhookEvent::Data _
      ) -> Imagekitio::FileDeletedWebhookEvent::Data

      def `type`: -> :"file.deleted"

      def type=: (:"file.deleted" _) -> :"file.deleted"

      def initialize: (
        created_at: Time,
        data: Imagekitio::FileDeletedWebhookEvent::Data,
        ?type: :"file.deleted"
      ) -> void

      def to_hash: -> {
        created_at: Time,
        data: Imagekitio::FileDeletedWebhookEvent::Data,
        type: :"file.deleted"
      }

      type data = { file_id: String }

      class Data < Imagekitio::Internal::Type::BaseModel
        attr_accessor file_id: String

        def initialize: (file_id: String) -> void

        def to_hash: -> { file_id: String }
      end
    end
  end
end
