module Imagekitio
  module Models
    type file_version_create_event =
      {
        created_at: Time,
        data: Imagekitio::File,
        type: :"file-version.created"
      }

    class FileVersionCreateEvent < Imagekitio::Models::BaseWebhookEvent
      def created_at: -> Time

      def created_at=: (Time _) -> Time

      def data: -> Imagekitio::File

      def data=: (Imagekitio::File _) -> Imagekitio::File

      def `type`: -> :"file-version.created"

      def type=: (:"file-version.created" _) -> :"file-version.created"

      def initialize: (
        created_at: Time,
        data: Imagekitio::File,
        ?type: :"file-version.created"
      ) -> void

      def to_hash: -> {
        created_at: Time,
        data: Imagekitio::File,
        type: :"file-version.created"
      }
    end
  end
end
