module Imagekitio
  module Models
    type file =
      {
        ai_tags: ::Array[Imagekitio::File::AITag]?,
        created_at: Time,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        file_id: String,
        file_path: String,
        file_type: String,
        has_alpha: bool,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        mime: String,
        name: String,
        selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema],
        size: Float,
        tags: ::Array[String]?,
        thumbnail: String,
        type: Imagekitio::Models::File::type_,
        updated_at: Time,
        url: String,
        version_info: Imagekitio::File::VersionInfo,
        width: Float
      }

    class File < Imagekitio::Internal::Type::BaseModel
      attr_accessor ai_tags: ::Array[Imagekitio::File::AITag]?

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      attr_accessor custom_coordinates: String?

      attr_reader custom_metadata: ::Hash[Symbol, top]?

      def custom_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader file_id: String?

      def file_id=: (String) -> String

      attr_reader file_path: String?

      def file_path=: (String) -> String

      attr_reader file_type: String?

      def file_type=: (String) -> String

      attr_reader has_alpha: bool?

      def has_alpha=: (bool) -> bool

      attr_reader height: Float?

      def height=: (Float) -> Float

      attr_reader is_private_file: bool?

      def is_private_file=: (bool) -> bool

      attr_reader is_published: bool?

      def is_published=: (bool) -> bool

      attr_reader mime: String?

      def mime=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema]?

      def selected_fields_schema=: (
        ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema]
      ) -> ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema]

      attr_reader size: Float?

      def size=: (Float) -> Float

      attr_accessor tags: ::Array[String]?

      attr_reader thumbnail: String?

      def thumbnail=: (String) -> String

      attr_reader type: Imagekitio::Models::File::type_?

      def type=: (
        Imagekitio::Models::File::type_
      ) -> Imagekitio::Models::File::type_

      attr_reader updated_at: Time?

      def updated_at=: (Time) -> Time

      attr_reader url: String?

      def url=: (String) -> String

      attr_reader version_info: Imagekitio::File::VersionInfo?

      def version_info=: (
        Imagekitio::File::VersionInfo
      ) -> Imagekitio::File::VersionInfo

      attr_reader width: Float?

      def width=: (Float) -> Float

      def initialize: (
        ?ai_tags: ::Array[Imagekitio::File::AITag]?,
        ?created_at: Time,
        ?custom_coordinates: String?,
        ?custom_metadata: ::Hash[Symbol, top],
        ?description: String,
        ?file_id: String,
        ?file_path: String,
        ?file_type: String,
        ?has_alpha: bool,
        ?height: Float,
        ?is_private_file: bool,
        ?is_published: bool,
        ?mime: String,
        ?name: String,
        ?selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema],
        ?size: Float,
        ?tags: ::Array[String]?,
        ?thumbnail: String,
        ?type: Imagekitio::Models::File::type_,
        ?updated_at: Time,
        ?url: String,
        ?version_info: Imagekitio::File::VersionInfo,
        ?width: Float
      ) -> void

      def to_hash: -> {
        ai_tags: ::Array[Imagekitio::File::AITag]?,
        created_at: Time,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        file_id: String,
        file_path: String,
        file_type: String,
        has_alpha: bool,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        mime: String,
        name: String,
        selected_fields_schema: ::Hash[Symbol, Imagekitio::File::SelectedFieldsSchema],
        size: Float,
        tags: ::Array[String]?,
        thumbnail: String,
        type: Imagekitio::Models::File::type_,
        updated_at: Time,
        url: String,
        version_info: Imagekitio::File::VersionInfo,
        width: Float
      }

      type ai_tag = { confidence: Float, name: String, source: String }

      class AITag < Imagekitio::Internal::Type::BaseModel
        attr_reader confidence: Float?

        def confidence=: (Float) -> Float

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader source: String?

        def source=: (String) -> String

        def initialize: (
          ?confidence: Float,
          ?name: String,
          ?source: String
        ) -> void

        def to_hash: -> { confidence: Float, name: String, source: String }
      end

      type selected_fields_schema =
        {
          type: Imagekitio::Models::File::SelectedFieldsSchema::type_,
          default_value: Imagekitio::Models::File::SelectedFieldsSchema::default_value,
          is_value_required: bool,
          max_length: Float,
          max_value: Imagekitio::Models::File::SelectedFieldsSchema::max_value,
          min_length: Float,
          min_value: Imagekitio::Models::File::SelectedFieldsSchema::min_value,
          read_only: bool,
          select_options: ::Array[Imagekitio::Models::File::SelectedFieldsSchema::select_option],
          select_options_truncated: bool
        }

      class SelectedFieldsSchema < Imagekitio::Internal::Type::BaseModel
        attr_accessor type: Imagekitio::Models::File::SelectedFieldsSchema::type_

        attr_reader default_value: Imagekitio::Models::File::SelectedFieldsSchema::default_value?

        def default_value=: (
          Imagekitio::Models::File::SelectedFieldsSchema::default_value
        ) -> Imagekitio::Models::File::SelectedFieldsSchema::default_value

        attr_reader is_value_required: bool?

        def is_value_required=: (bool) -> bool

        attr_reader max_length: Float?

        def max_length=: (Float) -> Float

        attr_reader max_value: Imagekitio::Models::File::SelectedFieldsSchema::max_value?

        def max_value=: (
          Imagekitio::Models::File::SelectedFieldsSchema::max_value
        ) -> Imagekitio::Models::File::SelectedFieldsSchema::max_value

        attr_reader min_length: Float?

        def min_length=: (Float) -> Float

        attr_reader min_value: Imagekitio::Models::File::SelectedFieldsSchema::min_value?

        def min_value=: (
          Imagekitio::Models::File::SelectedFieldsSchema::min_value
        ) -> Imagekitio::Models::File::SelectedFieldsSchema::min_value

        attr_reader read_only: bool?

        def read_only=: (bool) -> bool

        attr_reader select_options: ::Array[Imagekitio::Models::File::SelectedFieldsSchema::select_option]?

        def select_options=: (
          ::Array[Imagekitio::Models::File::SelectedFieldsSchema::select_option]
        ) -> ::Array[Imagekitio::Models::File::SelectedFieldsSchema::select_option]

        attr_reader select_options_truncated: bool?

        def select_options_truncated=: (bool) -> bool

        def initialize: (
          type: Imagekitio::Models::File::SelectedFieldsSchema::type_,
          ?default_value: Imagekitio::Models::File::SelectedFieldsSchema::default_value,
          ?is_value_required: bool,
          ?max_length: Float,
          ?max_value: Imagekitio::Models::File::SelectedFieldsSchema::max_value,
          ?min_length: Float,
          ?min_value: Imagekitio::Models::File::SelectedFieldsSchema::min_value,
          ?read_only: bool,
          ?select_options: ::Array[Imagekitio::Models::File::SelectedFieldsSchema::select_option],
          ?select_options_truncated: bool
        ) -> void

        def to_hash: -> {
          type: Imagekitio::Models::File::SelectedFieldsSchema::type_,
          default_value: Imagekitio::Models::File::SelectedFieldsSchema::default_value,
          is_value_required: bool,
          max_length: Float,
          max_value: Imagekitio::Models::File::SelectedFieldsSchema::max_value,
          min_length: Float,
          min_value: Imagekitio::Models::File::SelectedFieldsSchema::min_value,
          read_only: bool,
          select_options: ::Array[Imagekitio::Models::File::SelectedFieldsSchema::select_option],
          select_options_truncated: bool
        }

        type type_ =
          :Text
          | :Textarea
          | :Number
          | :Date
          | :Boolean
          | :SingleSelect
          | :MultiSelect

        module Type
          extend Imagekitio::Internal::Type::Enum

          TEXT: :Text
          TEXTAREA: :Textarea
          NUMBER: :Number
          DATE: :Date
          BOOLEAN: :Boolean
          SINGLE_SELECT: :SingleSelect
          MULTI_SELECT: :MultiSelect

          def self?.values: -> ::Array[Imagekitio::Models::File::SelectedFieldsSchema::type_]
        end

        type default_value =
          String
          | Float
          | bool
          | ::Array[Imagekitio::Models::File::SelectedFieldsSchema::DefaultValue::mixed]

        module DefaultValue
          extend Imagekitio::Internal::Type::Union

          type mixed = String | Float | bool

          module Mixed
            extend Imagekitio::Internal::Type::Union

            def self?.variants: -> ::Array[Imagekitio::Models::File::SelectedFieldsSchema::DefaultValue::mixed]
          end

          def self?.variants: -> ::Array[Imagekitio::Models::File::SelectedFieldsSchema::default_value]

          MixedArray: Imagekitio::Internal::Type::Converter
        end

        type max_value = String | Float

        module MaxValue
          extend Imagekitio::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekitio::Models::File::SelectedFieldsSchema::max_value]
        end

        type min_value = String | Float

        module MinValue
          extend Imagekitio::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekitio::Models::File::SelectedFieldsSchema::min_value]
        end

        type select_option = String | Float | bool

        module SelectOption
          extend Imagekitio::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekitio::Models::File::SelectedFieldsSchema::select_option]
        end
      end

      type type_ = :file | :"file-version"

      module Type
        extend Imagekitio::Internal::Type::Enum

        FILE: :file
        FILE_VERSION: :"file-version"

        def self?.values: -> ::Array[Imagekitio::Models::File::type_]
      end

      type version_info = { id: String, name: String }

      class VersionInfo < Imagekitio::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (?id: String, ?name: String) -> void

        def to_hash: -> { id: String, name: String }
      end
    end
  end
end
