module Imagekitio
  module Models
    type file_upload_response =
      {
        ai_tags: ::Array[Imagekitio::Models::FileUploadResponse::AITag]?,
        audio_codec: String,
        bit_rate: Integer,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        duration: Integer,
        embedded_metadata: ::Hash[Symbol, top],
        extension_status: Imagekitio::Models::FileUploadResponse::ExtensionStatus,
        file_id: String,
        file_path: String,
        file_type: String,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        metadata: Imagekitio::Metadata,
        name: String,
        selected_fields_schema: ::Hash[Symbol, Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema],
        size: Float,
        tags: ::Array[String]?,
        thumbnail_url: String,
        url: String,
        version_info: Imagekitio::Models::FileUploadResponse::VersionInfo,
        video_codec: String,
        width: Float
      }

    class FileUploadResponse < Imagekitio::Internal::Type::BaseModel
      attr_accessor ai_tags: ::Array[Imagekitio::Models::FileUploadResponse::AITag]?

      attr_reader audio_codec: String?

      def audio_codec=: (String) -> String

      attr_reader bit_rate: Integer?

      def bit_rate=: (Integer) -> Integer

      attr_accessor custom_coordinates: String?

      attr_reader custom_metadata: ::Hash[Symbol, top]?

      def custom_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader duration: Integer?

      def duration=: (Integer) -> Integer

      attr_reader embedded_metadata: ::Hash[Symbol, top]?

      def embedded_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader extension_status: Imagekitio::Models::FileUploadResponse::ExtensionStatus?

      def extension_status=: (
        Imagekitio::Models::FileUploadResponse::ExtensionStatus
      ) -> Imagekitio::Models::FileUploadResponse::ExtensionStatus

      attr_reader file_id: String?

      def file_id=: (String) -> String

      attr_reader file_path: String?

      def file_path=: (String) -> String

      attr_reader file_type: String?

      def file_type=: (String) -> String

      attr_reader height: Float?

      def height=: (Float) -> Float

      attr_reader is_private_file: bool?

      def is_private_file=: (bool) -> bool

      attr_reader is_published: bool?

      def is_published=: (bool) -> bool

      attr_reader metadata: Imagekitio::Metadata?

      def metadata=: (Imagekitio::Metadata) -> Imagekitio::Metadata

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader selected_fields_schema: ::Hash[Symbol, Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema]?

      def selected_fields_schema=: (
        ::Hash[Symbol, Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema]
      ) -> ::Hash[Symbol, Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema]

      attr_reader size: Float?

      def size=: (Float) -> Float

      attr_accessor tags: ::Array[String]?

      attr_reader thumbnail_url: String?

      def thumbnail_url=: (String) -> String

      attr_reader url: String?

      def url=: (String) -> String

      attr_reader version_info: Imagekitio::Models::FileUploadResponse::VersionInfo?

      def version_info=: (
        Imagekitio::Models::FileUploadResponse::VersionInfo
      ) -> Imagekitio::Models::FileUploadResponse::VersionInfo

      attr_reader video_codec: String?

      def video_codec=: (String) -> String

      attr_reader width: Float?

      def width=: (Float) -> Float

      def initialize: (
        ?ai_tags: ::Array[Imagekitio::Models::FileUploadResponse::AITag]?,
        ?audio_codec: String,
        ?bit_rate: Integer,
        ?custom_coordinates: String?,
        ?custom_metadata: ::Hash[Symbol, top],
        ?description: String,
        ?duration: Integer,
        ?embedded_metadata: ::Hash[Symbol, top],
        ?extension_status: Imagekitio::Models::FileUploadResponse::ExtensionStatus,
        ?file_id: String,
        ?file_path: String,
        ?file_type: String,
        ?height: Float,
        ?is_private_file: bool,
        ?is_published: bool,
        ?metadata: Imagekitio::Metadata,
        ?name: String,
        ?selected_fields_schema: ::Hash[Symbol, Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema],
        ?size: Float,
        ?tags: ::Array[String]?,
        ?thumbnail_url: String,
        ?url: String,
        ?version_info: Imagekitio::Models::FileUploadResponse::VersionInfo,
        ?video_codec: String,
        ?width: Float
      ) -> void

      def to_hash: -> {
        ai_tags: ::Array[Imagekitio::Models::FileUploadResponse::AITag]?,
        audio_codec: String,
        bit_rate: Integer,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        description: String,
        duration: Integer,
        embedded_metadata: ::Hash[Symbol, top],
        extension_status: Imagekitio::Models::FileUploadResponse::ExtensionStatus,
        file_id: String,
        file_path: String,
        file_type: String,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        metadata: Imagekitio::Metadata,
        name: String,
        selected_fields_schema: ::Hash[Symbol, Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema],
        size: Float,
        tags: ::Array[String]?,
        thumbnail_url: String,
        url: String,
        version_info: Imagekitio::Models::FileUploadResponse::VersionInfo,
        video_codec: String,
        width: Float
      }

      type ai_tag = { confidence: Float, name: String, source: String }

      class AITag < Imagekitio::Internal::Type::BaseModel
        attr_reader confidence: Float?

        def confidence=: (Float) -> Float

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader source: String?

        def source=: (String) -> String

        def initialize: (
          ?confidence: Float,
          ?name: String,
          ?source: String
        ) -> void

        def to_hash: -> { confidence: Float, name: String, source: String }
      end

      type extension_status =
        {
          ai_auto_description: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_auto_description,
          ai_tasks: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_tasks,
          aws_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging,
          google_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging,
          remove_bg: Imagekitio::Models::FileUploadResponse::ExtensionStatus::remove_bg
        }

      class ExtensionStatus < Imagekitio::Internal::Type::BaseModel
        attr_reader ai_auto_description: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_auto_description?

        def ai_auto_description=: (
          Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_auto_description
        ) -> Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_auto_description

        attr_reader ai_tasks: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_tasks?

        def ai_tasks=: (
          Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_tasks
        ) -> Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_tasks

        attr_reader aws_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging?

        def aws_auto_tagging=: (
          Imagekitio::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging
        ) -> Imagekitio::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging

        attr_reader google_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging?

        def google_auto_tagging=: (
          Imagekitio::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging
        ) -> Imagekitio::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging

        attr_reader remove_bg: Imagekitio::Models::FileUploadResponse::ExtensionStatus::remove_bg?

        def remove_bg=: (
          Imagekitio::Models::FileUploadResponse::ExtensionStatus::remove_bg
        ) -> Imagekitio::Models::FileUploadResponse::ExtensionStatus::remove_bg

        def initialize: (
          ?ai_auto_description: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_auto_description,
          ?ai_tasks: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_tasks,
          ?aws_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging,
          ?google_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging,
          ?remove_bg: Imagekitio::Models::FileUploadResponse::ExtensionStatus::remove_bg
        ) -> void

        def to_hash: -> {
          ai_auto_description: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_auto_description,
          ai_tasks: Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_tasks,
          aws_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging,
          google_auto_tagging: Imagekitio::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging,
          remove_bg: Imagekitio::Models::FileUploadResponse::ExtensionStatus::remove_bg
        }

        type ai_auto_description = :success | :pending | :failed

        module AIAutoDescription
          extend Imagekitio::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_auto_description]
        end

        type ai_tasks = :success | :pending | :failed

        module AITasks
          extend Imagekitio::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekitio::Models::FileUploadResponse::ExtensionStatus::ai_tasks]
        end

        type aws_auto_tagging = :success | :pending | :failed

        module AwsAutoTagging
          extend Imagekitio::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekitio::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging]
        end

        type google_auto_tagging = :success | :pending | :failed

        module GoogleAutoTagging
          extend Imagekitio::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekitio::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging]
        end

        type remove_bg = :success | :pending | :failed

        module RemoveBg
          extend Imagekitio::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekitio::Models::FileUploadResponse::ExtensionStatus::remove_bg]
        end
      end

      type selected_fields_schema =
        {
          type: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::type_,
          default_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::default_value,
          is_value_required: bool,
          max_length: Float,
          max_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::max_value,
          min_length: Float,
          min_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::min_value,
          read_only: bool,
          select_options: ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::select_option],
          select_options_truncated: bool
        }

      class SelectedFieldsSchema < Imagekitio::Internal::Type::BaseModel
        attr_accessor type: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::type_

        attr_reader default_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::default_value?

        def default_value=: (
          Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::default_value
        ) -> Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::default_value

        attr_reader is_value_required: bool?

        def is_value_required=: (bool) -> bool

        attr_reader max_length: Float?

        def max_length=: (Float) -> Float

        attr_reader max_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::max_value?

        def max_value=: (
          Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::max_value
        ) -> Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::max_value

        attr_reader min_length: Float?

        def min_length=: (Float) -> Float

        attr_reader min_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::min_value?

        def min_value=: (
          Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::min_value
        ) -> Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::min_value

        attr_reader read_only: bool?

        def read_only=: (bool) -> bool

        attr_reader select_options: ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::select_option]?

        def select_options=: (
          ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::select_option]
        ) -> ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::select_option]

        attr_reader select_options_truncated: bool?

        def select_options_truncated=: (bool) -> bool

        def initialize: (
          type: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::type_,
          ?default_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::default_value,
          ?is_value_required: bool,
          ?max_length: Float,
          ?max_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::max_value,
          ?min_length: Float,
          ?min_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::min_value,
          ?read_only: bool,
          ?select_options: ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::select_option],
          ?select_options_truncated: bool
        ) -> void

        def to_hash: -> {
          type: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::type_,
          default_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::default_value,
          is_value_required: bool,
          max_length: Float,
          max_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::max_value,
          min_length: Float,
          min_value: Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::min_value,
          read_only: bool,
          select_options: ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::select_option],
          select_options_truncated: bool
        }

        type type_ =
          :Text
          | :Textarea
          | :Number
          | :Date
          | :Boolean
          | :SingleSelect
          | :MultiSelect

        module Type
          extend Imagekitio::Internal::Type::Enum

          TEXT: :Text
          TEXTAREA: :Textarea
          NUMBER: :Number
          DATE: :Date
          BOOLEAN: :Boolean
          SINGLE_SELECT: :SingleSelect
          MULTI_SELECT: :MultiSelect

          def self?.values: -> ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::type_]
        end

        type default_value =
          String
          | Float
          | bool
          | ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::DefaultValue::mixed]

        module DefaultValue
          extend Imagekitio::Internal::Type::Union

          type mixed = String | Float | bool

          module Mixed
            extend Imagekitio::Internal::Type::Union

            def self?.variants: -> ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::DefaultValue::mixed]
          end

          def self?.variants: -> ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::default_value]

          MixedArray: Imagekitio::Internal::Type::Converter
        end

        type max_value = String | Float

        module MaxValue
          extend Imagekitio::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::max_value]
        end

        type min_value = String | Float

        module MinValue
          extend Imagekitio::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::min_value]
        end

        type select_option = String | Float | bool

        module SelectOption
          extend Imagekitio::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekitio::Models::FileUploadResponse::SelectedFieldsSchema::select_option]
        end
      end

      type version_info = { id: String, name: String }

      class VersionInfo < Imagekitio::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (?id: String, ?name: String) -> void

        def to_hash: -> { id: String, name: String }
      end
    end
  end
end
