module Imagekitio
  module Models
    type folder_rename_response = { job_id: String }

    class FolderRenameResponse < Imagekitio::Internal::Type::BaseModel
      attr_accessor job_id: String

      def initialize: (job_id: String) -> void

      def to_hash: -> { job_id: String }
    end
  end
end
