module Imagekitio
  module Models
    type image_overlay =
      {
        input: String,
        type: :image,
        encoding: Imagekitio::Models::ImageOverlay::encoding,
        transformation: ::Array[Imagekitio::Transformation]
      }

    class ImageOverlay < Imagekitio::Models::BaseOverlay
      def input: -> String

      def input=: (String _) -> String

      def `type`: -> :image

      def type=: (:image _) -> :image

      def encoding: -> Imagekitio::Models::ImageOverlay::encoding?

      def encoding=: (
        Imagekitio::Models::ImageOverlay::encoding _
      ) -> Imagekitio::Models::ImageOverlay::encoding

      def transformation: -> ::Array[Imagekitio::Transformation]?

      def transformation=: (
        ::Array[Imagekitio::Transformation] _
      ) -> ::Array[Imagekitio::Transformation]

      def initialize: (
        input: String,
        ?encoding: Imagekitio::Models::ImageOverlay::encoding,
        ?transformation: ::Array[Imagekitio::Transformation],
        ?type: :image
      ) -> void

      def to_hash: -> {
        input: String,
        type: :image,
        encoding: Imagekitio::Models::ImageOverlay::encoding,
        transformation: ::Array[Imagekitio::Transformation]
      }

      type encoding = :auto | :plain | :base64

      module Encoding
        extend Imagekitio::Internal::Type::Enum

        AUTO: :auto
        PLAIN: :plain
        BASE64: :base64

        def self?.values: -> ::Array[Imagekitio::Models::ImageOverlay::encoding]
      end
    end
  end
end
