module Imagekitio
  module Models
    type named_transformation =
      {
        id: String,
        created_at: Time,
        enabled: bool,
        name: String,
        transformation: String
      }

    class NamedTransformation < Imagekitio::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor enabled: bool

      attr_accessor name: String

      attr_accessor transformation: String

      def initialize: (
        id: String,
        created_at: Time,
        enabled: bool,
        name: String,
        transformation: String
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        enabled: bool,
        name: String,
        transformation: String
      }
    end
  end
end
