module Imagekitio
  module Models
    type saved_extension_update_params =
      {
        config: Imagekitio::Models::extension_config,
        description: String,
        name: String
      }
      & Imagekitio::Internal::Type::request_parameters

    class SavedExtensionUpdateParams < Imagekitio::Internal::Type::BaseModel
      extend Imagekitio::Internal::Type::RequestParameters::Converter
      include Imagekitio::Internal::Type::RequestParameters

      attr_reader config: Imagekitio::Models::extension_config?

      def config=: (
        Imagekitio::Models::extension_config
      ) -> Imagekitio::Models::extension_config

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        ?config: Imagekitio::Models::extension_config,
        ?description: String,
        ?name: String,
        ?request_options: Imagekitio::request_opts
      ) -> void

      def to_hash: -> {
        config: Imagekitio::Models::extension_config,
        description: String,
        name: String,
        request_options: Imagekitio::RequestOptions
      }
    end
  end
end
