module Imagekitio
  module Models
    type streaming_resolution =
      :"240" | :"360" | :"480" | :"720" | :"1080" | :"1440" | :"2160"

    module StreamingResolution
      extend Imagekitio::Internal::Type::Enum

      STREAMING_RESOLUTION_240: :"240"
      STREAMING_RESOLUTION_360: :"360"
      STREAMING_RESOLUTION_480: :"480"
      STREAMING_RESOLUTION_720: :"720"
      STREAMING_RESOLUTION_1080: :"1080"
      STREAMING_RESOLUTION_1440: :"1440"
      STREAMING_RESOLUTION_2160: :"2160"

      def self?.values: -> ::Array[Imagekitio::Models::streaming_resolution]
    end
  end
end
