module Imagekitio
  module Models
    type subtitle_overlay =
      {
        input: String,
        type: :subtitle,
        encoding: Imagekitio::Models::SubtitleOverlay::encoding,
        transformation: ::Array[Imagekitio::SubtitleOverlayTransformation]
      }

    class SubtitleOverlay < Imagekitio::Models::BaseOverlay
      def input: -> String

      def input=: (String _) -> String

      def `type`: -> :subtitle

      def type=: (:subtitle _) -> :subtitle

      def encoding: -> Imagekitio::Models::SubtitleOverlay::encoding?

      def encoding=: (
        Imagekitio::Models::SubtitleOverlay::encoding _
      ) -> Imagekitio::Models::SubtitleOverlay::encoding

      def transformation: -> ::Array[Imagekitio::SubtitleOverlayTransformation]?

      def transformation=: (
        ::Array[Imagekitio::SubtitleOverlayTransformation] _
      ) -> ::Array[Imagekitio::SubtitleOverlayTransformation]

      def initialize: (
        input: String,
        ?encoding: Imagekitio::Models::SubtitleOverlay::encoding,
        ?transformation: ::Array[Imagekitio::SubtitleOverlayTransformation],
        ?type: :subtitle
      ) -> void

      def to_hash: -> {
        input: String,
        type: :subtitle,
        encoding: Imagekitio::Models::SubtitleOverlay::encoding,
        transformation: ::Array[Imagekitio::SubtitleOverlayTransformation]
      }

      type encoding = :auto | :plain | :base64

      module Encoding
        extend Imagekitio::Internal::Type::Enum

        AUTO: :auto
        PLAIN: :plain
        BASE64: :base64

        def self?.values: -> ::Array[Imagekitio::Models::SubtitleOverlay::encoding]
      end
    end
  end
end
