module Imagekitio
  module Models
    type unwrap_webhook_event =
      Imagekitio::VideoTransformationAcceptedEvent
      | Imagekitio::VideoTransformationReadyEvent
      | Imagekitio::VideoTransformationErrorEvent
      | Imagekitio::UploadPreTransformSuccessEvent
      | Imagekitio::UploadPreTransformErrorEvent
      | Imagekitio::UploadPostTransformSuccessEvent
      | Imagekitio::UploadPostTransformErrorEvent
      | Imagekitio::FileCreatedWebhookEvent
      | Imagekitio::FileUpdatedWebhookEvent
      | Imagekitio::FileDeletedWebhookEvent
      | Imagekitio::FileVersionCreatedWebhookEvent
      | Imagekitio::FileVersionDeletedWebhookEvent

    module UnwrapWebhookEvent
      extend Imagekitio::Internal::Type::Union

      def self?.variants: -> ::Array[Imagekitio::Models::unwrap_webhook_event]
    end
  end
end
