# frozen_string_literal: true

module Imagekitio
  module Models
    class NamedTransformation < Imagekitio::Internal::Type::BaseModel
      # @!attribute id
      #   Unique identifier of the named transformation. This is generated by ImageKit
      #   when you create a new named transformation.
      #
      #   @return [String, nil]
      optional :id, String

      # @!attribute created_at
      #   Timestamp when the named transformation was created.
      #
      #   @return [Time, nil]
      optional :created_at, Time, api_name: :createdAt

      # @!attribute disabled
      #   Whether this named transformation is currently disabled.
      #
      #   @return [Boolean, nil]
      optional :disabled, Imagekitio::Internal::Type::Boolean

      # @!attribute name
      #   Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
      #
      #   @return [String, nil]
      optional :name, String

      # @!attribute transformation
      #   The transformation string this name refers to.
      #
      #   @return [String, nil]
      optional :transformation, String

      # @!method initialize(id: nil, created_at: nil, disabled: nil, name: nil, transformation: nil)
      #   Some parameter documentations has been truncated, see
      #   {Imagekitio::Models::NamedTransformation} for more details.
      #
      #   A named transformation is an alias for an actual transformation string, allowing
      #   you to apply and later update complex transformations without changing your
      #   image or video URLs. Learn more about
      #   [named transformations](https://imagekit.io/docs/transformations#named-transformations).
      #
      #   @param id [String] Unique identifier of the named transformation. This is generated by ImageKit whe
      #
      #   @param created_at [Time] Timestamp when the named transformation was created.
      #
      #   @param disabled [Boolean] Whether this named transformation is currently disabled.
      #
      #   @param name [String] Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
      #
      #   @param transformation [String] The transformation string this name refers to.
    end
  end
end
