# frozen_string_literal: true

module Imagekitio
  module Models
    class NamedTransformation < Imagekitio::Internal::Type::BaseModel
      # @!attribute id
      #   Unique identifier generated by ImageKit when the named transformation was
      #   created.
      #
      #   @return [String, nil]
      optional :id, String

      # @!attribute created_at
      #   ISO 8601 timestamp of when the named transformation was created.
      #
      #   @return [Time, nil]
      optional :created_at, Time, api_name: :createdAt

      # @!attribute enabled
      #   Whether the named transformation is currently enabled.
      #
      #   @return [Boolean, nil]
      optional :enabled, Imagekitio::Internal::Type::Boolean

      # @!attribute name
      #   Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
      #
      #   @return [String, nil]
      optional :name, String

      # @!attribute transformation
      #   Transformation string this name refers to. Always includes the `tr:` prefix,
      #   even if you omitted it in the request.
      #
      #   @return [String, nil]
      optional :transformation, String

      # @!method initialize(id: nil, created_at: nil, enabled: nil, name: nil, transformation: nil)
      #   Some parameter documentations has been truncated, see
      #   {Imagekitio::Models::NamedTransformation} for more details.
      #
      #   A named transformation is an alias for a transformation string, letting you
      #   apply and later update complex transformations without changing your image or
      #   video URLs. Learn more about
      #   [named transformations](https://imagekit.io/docs/transformations#named-transformations).
      #
      #   @param id [String] Unique identifier generated by ImageKit when the named transformation was create
      #
      #   @param created_at [Time] ISO 8601 timestamp of when the named transformation was created.
      #
      #   @param enabled [Boolean] Whether the named transformation is currently enabled.
      #
      #   @param name [String] Name of the named transformation, used as `tr:n-<name>` in image and video URLs.
      #
      #   @param transformation [String] Transformation string this name refers to. Always includes the `tr:` prefix, eve
    end
  end
end
