# frozen_string_literal: true

module Imagekitio
  module Models
    module Accounts
      # Origin object as returned by the API (sensitive fields removed).
      #
      # @see Imagekitio::Resources::Accounts::Origins#create
      module OriginResponse
        extend Imagekitio::Internal::Type::Union

        discriminator :type

        variant :S3, -> { Imagekitio::Accounts::OriginResponse::S3 }

        variant :S3_COMPATIBLE, -> { Imagekitio::Accounts::OriginResponse::S3Compatible }

        variant :CLOUDINARY_BACKUP, -> { Imagekitio::Accounts::OriginResponse::CloudinaryBackup }

        variant :WEB_FOLDER, -> { Imagekitio::Accounts::OriginResponse::WebFolder }

        variant :WEB_PROXY, -> { Imagekitio::Accounts::OriginResponse::WebProxy }

        variant :GCS, -> { Imagekitio::Accounts::OriginResponse::Gcs }

        variant :AZURE_BLOB, -> { Imagekitio::Accounts::OriginResponse::AzureBlob }

        variant :AKENEO_PIM, -> { Imagekitio::Accounts::OriginResponse::AkeneoPim }

        class S3 < Imagekitio::Internal::Type::BaseModel
          # @!attribute bucket
          #   S3 bucket name.
          #
          #   @return [String]
          required :bucket, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #   Path prefix inside the bucket.
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, :S3]
          required :type, const: :S3

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, include_canonical_header:, name:, prefix:, base_url_for_canonical_header: nil, type: :S3)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::S3} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String] S3 bucket name.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String] Path prefix inside the bucket.
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :S3]
        end

        class S3Compatible < Imagekitio::Internal::Type::BaseModel
          # @!attribute bucket
          #   S3 bucket name.
          #
          #   @return [String]
          required :bucket, String

          # @!attribute endpoint
          #   Custom S3-compatible endpoint.
          #
          #   @return [String]
          required :endpoint, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #   Path prefix inside the bucket.
          #
          #   @return [String]
          required :prefix, String

          # @!attribute s3_force_path_style
          #   Use path-style S3 URLs?
          #
          #   @return [Boolean]
          required :s3_force_path_style, Imagekitio::Internal::Type::Boolean, api_name: :s3ForcePathStyle

          # @!attribute type
          #
          #   @return [Symbol, :S3_COMPATIBLE]
          required :type, const: :S3_COMPATIBLE

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, endpoint:, include_canonical_header:, name:, prefix:, s3_force_path_style:, base_url_for_canonical_header: nil, type: :S3_COMPATIBLE)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::S3Compatible} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String] S3 bucket name.
          #
          #   @param endpoint [String] Custom S3-compatible endpoint.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String] Path prefix inside the bucket.
          #
          #   @param s3_force_path_style [Boolean] Use path-style S3 URLs?
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :S3_COMPATIBLE]
        end

        class CloudinaryBackup < Imagekitio::Internal::Type::BaseModel
          # @!attribute bucket
          #   S3 bucket name.
          #
          #   @return [String]
          required :bucket, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #   Path prefix inside the bucket.
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, :CLOUDINARY_BACKUP]
          required :type, const: :CLOUDINARY_BACKUP

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, include_canonical_header:, name:, prefix:, base_url_for_canonical_header: nil, type: :CLOUDINARY_BACKUP)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::CloudinaryBackup} for more
          #   details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String] S3 bucket name.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String] Path prefix inside the bucket.
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :CLOUDINARY_BACKUP]
        end

        class WebFolder < Imagekitio::Internal::Type::BaseModel
          # @!attribute base_url
          #   Root URL for the web folder origin.
          #
          #   @return [String]
          required :base_url, String, api_name: :baseUrl

          # @!attribute forward_host_header_to_origin
          #   Forward the Host header to origin?
          #
          #   @return [Boolean]
          required :forward_host_header_to_origin,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :forwardHostHeaderToOrigin

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute type
          #
          #   @return [Symbol, :WEB_FOLDER]
          required :type, const: :WEB_FOLDER

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, base_url:, forward_host_header_to_origin:, include_canonical_header:, name:, base_url_for_canonical_header: nil, type: :WEB_FOLDER)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::WebFolder} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param base_url [String] Root URL for the web folder origin.
          #
          #   @param forward_host_header_to_origin [Boolean] Forward the Host header to origin?
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :WEB_FOLDER]
        end

        class WebProxy < Imagekitio::Internal::Type::BaseModel
          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute type
          #
          #   @return [Symbol, :WEB_PROXY]
          required :type, const: :WEB_PROXY

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, include_canonical_header:, name:, base_url_for_canonical_header: nil, type: :WEB_PROXY)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::WebProxy} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :WEB_PROXY]
        end

        class Gcs < Imagekitio::Internal::Type::BaseModel
          # @!attribute bucket
          #
          #   @return [String]
          required :bucket, String

          # @!attribute client_email
          #
          #   @return [String]
          required :client_email, String, api_name: :clientEmail

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, :GCS]
          required :type, const: :GCS

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, client_email:, include_canonical_header:, name:, prefix:, base_url_for_canonical_header: nil, type: :GCS)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::Gcs} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String]
          #
          #   @param client_email [String]
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :GCS]
        end

        class AzureBlob < Imagekitio::Internal::Type::BaseModel
          # @!attribute account_name
          #
          #   @return [String]
          required :account_name, String, api_name: :accountName

          # @!attribute container
          #
          #   @return [String]
          required :container, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, :AZURE_BLOB]
          required :type, const: :AZURE_BLOB

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, account_name:, container:, include_canonical_header:, name:, prefix:, base_url_for_canonical_header: nil, type: :AZURE_BLOB)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::AzureBlob} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param account_name [String]
          #
          #   @param container [String]
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :AZURE_BLOB]
        end

        class AkeneoPim < Imagekitio::Internal::Type::BaseModel
          # @!attribute base_url
          #   Akeneo instance base URL.
          #
          #   @return [String]
          required :base_url, String, api_name: :baseUrl

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekitio::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute type
          #
          #   @return [Symbol, :AKENEO_PIM]
          required :type, const: :AKENEO_PIM

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, base_url:, include_canonical_header:, name:, base_url_for_canonical_header: nil, type: :AKENEO_PIM)
          #   Some parameter documentations has been truncated, see
          #   {Imagekitio::Models::Accounts::OriginResponse::AkeneoPim} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param base_url [String] Akeneo instance base URL.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).
          #
          #   @param type [Symbol, :AKENEO_PIM]
        end

        # @!method self.variants
        #   @return [Array(Imagekitio::Models::Accounts::OriginResponse::S3, Imagekitio::Models::Accounts::OriginResponse::S3Compatible, Imagekitio::Models::Accounts::OriginResponse::CloudinaryBackup, Imagekitio::Models::Accounts::OriginResponse::WebFolder, Imagekitio::Models::Accounts::OriginResponse::WebProxy, Imagekitio::Models::Accounts::OriginResponse::Gcs, Imagekitio::Models::Accounts::OriginResponse::AzureBlob, Imagekitio::Models::Accounts::OriginResponse::AkeneoPim)]
      end
    end
  end
end
