# frozen_string_literal: true

module Imagekitio
  module Models
    module Accounts
      # @see Imagekitio::Resources::Accounts::Origins#delete
      class OriginDeleteParams < Imagekitio::Internal::Type::BaseModel
        extend Imagekitio::Internal::Type::RequestParameters::Converter
        include Imagekitio::Internal::Type::RequestParameters

        # @!attribute id
        #   Unique identifier for the origin. This is generated by ImageKit when you create
        #   a new origin.
        #
        #   @return [String]
        required :id, String

        # @!method initialize(id:, request_options: {})
        #   Some parameter documentations has been truncated, see
        #   {Imagekitio::Models::Accounts::OriginDeleteParams} for more details.
        #
        #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
        #
        #   @param request_options [Imagekitio::RequestOptions, Hash{Symbol=>Object}]
      end
    end
  end
end
