# frozen_string_literal: true

module Imagekitio
  module Models
    module Accounts
      # @see Imagekitio::Resources::Accounts::URLEndpoints#update
      class URLEndpointUpdateParams < Imagekitio::Models::Accounts::URLEndpointRequest
        extend Imagekitio::Internal::Type::RequestParameters::Converter
        include Imagekitio::Internal::Type::RequestParameters

        # @!attribute id
        #   Unique identifier for the URL-endpoint. This is generated by ImageKit when you
        #   create a new URL-endpoint. For the default URL-endpoint, this is always
        #   `default`.
        #
        #   @return [String]
        required :id, String

        # @!method initialize(id:, request_options: {})
        #   Some parameter documentations has been truncated, see
        #   {Imagekitio::Models::Accounts::URLEndpointUpdateParams} for more details.
        #
        #   @param id [String] Unique identifier for the URL-endpoint. This is generated by ImageKit when you c
        #
        #   @param request_options [Imagekitio::RequestOptions, Hash{Symbol=>Object}]
      end
    end
  end
end
