# frozen_string_literal: true

module Imagekitio
  module Models
    module Accounts
      # @see Imagekitio::Resources::Accounts::Webhooks#create
      class Webhook < Imagekitio::Internal::Type::BaseModel
        # @!attribute id
        #   Unique identifier for a webhook.
        #
        #   @return [String]
        required :id, String

        # @!attribute created_at
        #   ISO 8601 timestamp of when the webhook was created.
        #
        #   @return [Time]
        required :created_at, Time, api_name: :createdAt

        # @!attribute enabled
        #   Whether the webhook is enabled. When `false`, ImageKit doesn't send any events
        #   to the `endpoint`.
        #
        #   @return [Boolean]
        required :enabled, Imagekitio::Internal::Type::Boolean

        # @!attribute endpoint
        #   The URL where ImageKit sends webhook events as `POST` requests. Must use the
        #   `http` or `https` protocol, and must be unique across all webhooks for your
        #   account.
        #
        #   @return [String]
        required :endpoint, String

        # @!attribute events
        #   The event types this webhook is subscribed to. ImageKit sends a request to the
        #   `endpoint` only for these events.
        #
        #   @return [Array<Symbol, Imagekitio::Models::Accounts::WebhookEventType>]
        required :events, -> { Imagekitio::Internal::Type::ArrayOf[enum: Imagekitio::Accounts::WebhookEventType] }

        # @!attribute secret
        #   Signing secret generated by ImageKit, used to verify that webhook requests come
        #   from ImageKit. Starts with `whsec_`. This value can't be set or changed through
        #   the API. Learn more about
        #   [verifying webhook signatures](https://imagekit.io/docs/webhooks#verify-webhook-signature).
        #
        #   @return [String]
        required :secret, String

        # @!attribute updated_at
        #   ISO 8601 timestamp of when the webhook was last updated.
        #
        #   @return [Time]
        required :updated_at, Time, api_name: :updatedAt

        # @!method initialize(id:, created_at:, enabled:, endpoint:, events:, secret:, updated_at:)
        #   Some parameter documentations has been truncated, see
        #   {Imagekitio::Models::Accounts::Webhook} for more details.
        #
        #   A webhook is an HTTP endpoint that ImageKit notifies when subscribed events
        #   occur in your account. Learn more about
        #   [webhooks](https://imagekit.io/docs/webhooks).
        #
        #   @param id [String] Unique identifier for a webhook.
        #
        #   @param created_at [Time] ISO 8601 timestamp of when the webhook was created.
        #
        #   @param enabled [Boolean] Whether the webhook is enabled. When `false`, ImageKit doesn't send any events t
        #
        #   @param endpoint [String] The URL where ImageKit sends webhook events as `POST` requests. Must use the `ht
        #
        #   @param events [Array<Symbol, Imagekitio::Models::Accounts::WebhookEventType>] The event types this webhook is subscribed to. ImageKit sends a request to the `
        #
        #   @param secret [String] Signing secret generated by ImageKit, used to verify that webhook requests come
        #
        #   @param updated_at [Time] ISO 8601 timestamp of when the webhook was last updated.
      end
    end
  end
end
