module Imagekit
  module Helpers
    class Helper
      def initialize: (client: Imagekit::Client) -> void

      # Builds a URL with transformations applied
      def buildURL: (Array[Imagekit::Models::Transformation] transformations) -> String

      # Generates transformation string from transformation objects
      def buildTransformationString: (Array[Imagekit::Models::Transformation] transformations) -> String

      # Gets authentication parameters for ImageKit requests
      def GetAuthenticationParameters: (?String? token) -> Hash[Symbol, (String | Integer)]
    end
  end
end
