module Imagekit
  module Models
    type asset_list_params =
      {
        file_type: Imagekit::Models::AssetListParams::file_type,
        limit: Integer,
        path: String,
        search_query: String,
        skip: Integer,
        sort: Imagekit::Models::AssetListParams::sort,
        type: Imagekit::Models::AssetListParams::type_
      }
      & Imagekit::Internal::Type::request_parameters

    class AssetListParams < Imagekit::Internal::Type::BaseModel
      extend Imagekit::Internal::Type::RequestParameters::Converter
      include Imagekit::Internal::Type::RequestParameters

      attr_reader file_type: Imagekit::Models::AssetListParams::file_type?

      def file_type=: (
        Imagekit::Models::AssetListParams::file_type
      ) -> Imagekit::Models::AssetListParams::file_type

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader path: String?

      def path=: (String) -> String

      attr_reader search_query: String?

      def search_query=: (String) -> String

      attr_reader skip: Integer?

      def skip=: (Integer) -> Integer

      attr_reader sort: Imagekit::Models::AssetListParams::sort?

      def sort=: (
        Imagekit::Models::AssetListParams::sort
      ) -> Imagekit::Models::AssetListParams::sort

      attr_reader type: Imagekit::Models::AssetListParams::type_?

      def type=: (
        Imagekit::Models::AssetListParams::type_
      ) -> Imagekit::Models::AssetListParams::type_

      def initialize: (
        ?file_type: Imagekit::Models::AssetListParams::file_type,
        ?limit: Integer,
        ?path: String,
        ?search_query: String,
        ?skip: Integer,
        ?sort: Imagekit::Models::AssetListParams::sort,
        ?type: Imagekit::Models::AssetListParams::type_,
        ?request_options: Imagekit::request_opts
      ) -> void

      def to_hash: -> {
        file_type: Imagekit::Models::AssetListParams::file_type,
        limit: Integer,
        path: String,
        search_query: String,
        skip: Integer,
        sort: Imagekit::Models::AssetListParams::sort,
        type: Imagekit::Models::AssetListParams::type_,
        request_options: Imagekit::RequestOptions
      }

      type file_type = :all | :image | :"non-image"

      module FileType
        extend Imagekit::Internal::Type::Enum

        ALL: :all
        IMAGE: :image
        NON_IMAGE: :"non-image"

        def self?.values: -> ::Array[Imagekit::Models::AssetListParams::file_type]
      end

      type sort =
        :ASC_NAME
        | :DESC_NAME
        | :ASC_CREATED
        | :DESC_CREATED
        | :ASC_UPDATED
        | :DESC_UPDATED
        | :ASC_HEIGHT
        | :DESC_HEIGHT
        | :ASC_WIDTH
        | :DESC_WIDTH
        | :ASC_SIZE
        | :DESC_SIZE
        | :ASC_RELEVANCE
        | :DESC_RELEVANCE

      module Sort
        extend Imagekit::Internal::Type::Enum

        ASC_NAME: :ASC_NAME
        DESC_NAME: :DESC_NAME
        ASC_CREATED: :ASC_CREATED
        DESC_CREATED: :DESC_CREATED
        ASC_UPDATED: :ASC_UPDATED
        DESC_UPDATED: :DESC_UPDATED
        ASC_HEIGHT: :ASC_HEIGHT
        DESC_HEIGHT: :DESC_HEIGHT
        ASC_WIDTH: :ASC_WIDTH
        DESC_WIDTH: :DESC_WIDTH
        ASC_SIZE: :ASC_SIZE
        DESC_SIZE: :DESC_SIZE
        ASC_RELEVANCE: :ASC_RELEVANCE
        DESC_RELEVANCE: :DESC_RELEVANCE

        def self?.values: -> ::Array[Imagekit::Models::AssetListParams::sort]
      end

      type type_ = :file | :"file-version" | :folder | :all

      module Type
        extend Imagekit::Internal::Type::Enum

        FILE: :file
        FILE_VERSION: :"file-version"
        FOLDER: :folder
        ALL: :all

        def self?.values: -> ::Array[Imagekit::Models::AssetListParams::type_]
      end
    end
  end
end
