module Imagekit
  module Models
    type auto_description_extension =
      { name: Imagekit::Models::AutoDescriptionExtension::name_ }

    class AutoDescriptionExtension < Imagekit::Internal::Type::BaseModel
      attr_accessor name: Imagekit::Models::AutoDescriptionExtension::name_

      def initialize: (
        name: Imagekit::Models::AutoDescriptionExtension::name_
      ) -> void

      def to_hash: -> {
        name: Imagekit::Models::AutoDescriptionExtension::name_
      }

      type name_ = :"ai-auto-description"

      module Name
        extend Imagekit::Internal::Type::Enum

        AI_AUTO_DESCRIPTION: :"ai-auto-description"

        def self?.values: -> ::Array[Imagekit::Models::AutoDescriptionExtension::name_]
      end
    end
  end
end
