module Imagekit
  module Models
    type base_webhook_event = { id: String, type: String }

    class BaseWebhookEvent < Imagekit::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor type: String

      def initialize: (id: String, type: String) -> void

      def to_hash: -> { id: String, type: String }
    end
  end
end
