module Imagekit
  module Models
    type bulk_job_retrieve_status_response =
      { job_id: String, status: String, type: String }

    class BulkJobRetrieveStatusResponse < Imagekit::Internal::Type::BaseModel
      attr_reader job_id: String?

      def job_id=: (String) -> String

      attr_reader status: String?

      def status=: (String) -> String

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (?job_id: String, ?status: String, ?type: String) -> void

      def to_hash: -> { job_id: String, status: String, type: String }
    end
  end
end
