module Imagekit
  module Models
    type bulk_job_copy_folder_params =
      {
        destination_path: String,
        source_folder_path: String,
        include_versions: bool
      }
      & Imagekit::Internal::Type::request_parameters

    class BulkJobCopyFolderParams < Imagekit::Internal::Type::BaseModel
      extend Imagekit::Internal::Type::RequestParameters::Converter
      include Imagekit::Internal::Type::RequestParameters

      attr_accessor destination_path: String

      attr_accessor source_folder_path: String

      attr_reader include_versions: bool?

      def include_versions=: (bool) -> bool

      def initialize: (
        destination_path: String,
        source_folder_path: String,
        ?include_versions: bool,
        ?request_options: Imagekit::request_opts
      ) -> void

      def to_hash: -> {
        destination_path: String,
        source_folder_path: String,
        include_versions: bool,
        request_options: Imagekit::RequestOptions
      }
    end
  end
end
