module Imagekit
  module Models
    type custom_metadata_field_create_response =
      {
        id: String,
        label: String,
        name: String,
        schema: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema
      }

    class CustomMetadataFieldCreateResponse < Imagekit::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor label: String

      attr_accessor name: String

      attr_accessor schema: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema

      def initialize: (
        id: String,
        label: String,
        name: String,
        schema: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema
      ) -> void

      def to_hash: -> {
        id: String,
        label: String,
        name: String,
        schema: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema
      }

      type schema =
        {
          type: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::type_,
          default_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::default_value,
          is_value_required: bool,
          max_length: Float,
          max_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::max_value,
          min_length: Float,
          min_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::min_value,
          select_options: ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::select_option]
        }

      class Schema < Imagekit::Internal::Type::BaseModel
        attr_accessor type: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::type_

        attr_reader default_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::default_value?

        def default_value=: (
          Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::default_value
        ) -> Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::default_value

        attr_reader is_value_required: bool?

        def is_value_required=: (bool) -> bool

        attr_reader max_length: Float?

        def max_length=: (Float) -> Float

        attr_reader max_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::max_value?

        def max_value=: (
          Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::max_value
        ) -> Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::max_value

        attr_reader min_length: Float?

        def min_length=: (Float) -> Float

        attr_reader min_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::min_value?

        def min_value=: (
          Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::min_value
        ) -> Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::min_value

        attr_reader select_options: ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::select_option]?

        def select_options=: (
          ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::select_option]
        ) -> ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::select_option]

        def initialize: (
          type: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::type_,
          ?default_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::default_value,
          ?is_value_required: bool,
          ?max_length: Float,
          ?max_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::max_value,
          ?min_length: Float,
          ?min_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::min_value,
          ?select_options: ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::select_option]
        ) -> void

        def to_hash: -> {
          type: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::type_,
          default_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::default_value,
          is_value_required: bool,
          max_length: Float,
          max_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::max_value,
          min_length: Float,
          min_value: Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::min_value,
          select_options: ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::select_option]
        }

        type type_ =
          :Text
          | :Textarea
          | :Number
          | :Date
          | :Boolean
          | :SingleSelect
          | :MultiSelect

        module Type
          extend Imagekit::Internal::Type::Enum

          TEXT: :Text
          TEXTAREA: :Textarea
          NUMBER: :Number
          DATE: :Date
          BOOLEAN: :Boolean
          SINGLE_SELECT: :SingleSelect
          MULTI_SELECT: :MultiSelect

          def self?.values: -> ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::type_]
        end

        type default_value =
          String
          | Float
          | bool
          | ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::DefaultValue::mixed]

        module DefaultValue
          extend Imagekit::Internal::Type::Union

          type mixed = String | Float | bool

          module Mixed
            extend Imagekit::Internal::Type::Union

            def self?.variants: -> ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::DefaultValue::mixed]
          end

          def self?.variants: -> ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::default_value]

          MixedArray: Imagekit::Internal::Type::Converter
        end

        type max_value = String | Float

        module MaxValue
          extend Imagekit::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::max_value]
        end

        type min_value = String | Float

        module MinValue
          extend Imagekit::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::min_value]
        end

        type select_option = String | Float | bool

        module SelectOption
          extend Imagekit::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekit::Models::CustomMetadataFieldCreateResponse::Schema::select_option]
        end
      end
    end
  end
end
