module Imagekit
  module Models
    type custom_metadata_field_list_params =
      { include_deleted: bool } & Imagekit::Internal::Type::request_parameters

    class CustomMetadataFieldListParams < Imagekit::Internal::Type::BaseModel
      extend Imagekit::Internal::Type::RequestParameters::Converter
      include Imagekit::Internal::Type::RequestParameters

      attr_reader include_deleted: bool?

      def include_deleted=: (bool) -> bool

      def initialize: (
        ?include_deleted: bool,
        ?request_options: Imagekit::request_opts
      ) -> void

      def to_hash: -> {
        include_deleted: bool,
        request_options: Imagekit::RequestOptions
      }
    end
  end
end
