module Imagekit
  module Models
    type exif_image =
      {
        exif_offset: Integer,
        gps_info: Integer,
        make: String,
        model: String,
        modify_date: String,
        orientation: Integer,
        resolution_unit: Integer,
        software: String,
        x_resolution: Integer,
        y_cb_cr_positioning: Integer,
        y_resolution: Integer
      }

    class ExifImage < Imagekit::Internal::Type::BaseModel
      attr_reader exif_offset: Integer?

      def exif_offset=: (Integer) -> Integer

      attr_reader gps_info: Integer?

      def gps_info=: (Integer) -> Integer

      attr_reader make: String?

      def make=: (String) -> String

      attr_reader model: String?

      def model=: (String) -> String

      attr_reader modify_date: String?

      def modify_date=: (String) -> String

      attr_reader orientation: Integer?

      def orientation=: (Integer) -> Integer

      attr_reader resolution_unit: Integer?

      def resolution_unit=: (Integer) -> Integer

      attr_reader software: String?

      def software=: (String) -> String

      attr_reader x_resolution: Integer?

      def x_resolution=: (Integer) -> Integer

      attr_reader y_cb_cr_positioning: Integer?

      def y_cb_cr_positioning=: (Integer) -> Integer

      attr_reader y_resolution: Integer?

      def y_resolution=: (Integer) -> Integer

      def initialize: (
        ?exif_offset: Integer,
        ?gps_info: Integer,
        ?make: String,
        ?model: String,
        ?modify_date: String,
        ?orientation: Integer,
        ?resolution_unit: Integer,
        ?software: String,
        ?x_resolution: Integer,
        ?y_cb_cr_positioning: Integer,
        ?y_resolution: Integer
      ) -> void

      def to_hash: -> {
        exif_offset: Integer,
        gps_info: Integer,
        make: String,
        model: String,
        modify_date: String,
        orientation: Integer,
        resolution_unit: Integer,
        software: String,
        x_resolution: Integer,
        y_cb_cr_positioning: Integer,
        y_resolution: Integer
      }
    end
  end
end
