module Imagekit
  module Models
    type exif_details =
      {
        aperture_value: Float,
        color_space: Integer,
        create_date: String,
        custom_rendered: Integer,
        date_time_original: String,
        exif_image_height: Integer,
        exif_image_width: Integer,
        exif_version: String,
        exposure_compensation: Float,
        exposure_mode: Integer,
        exposure_program: Integer,
        exposure_time: Float,
        flash: Integer,
        flashpix_version: String,
        f_number: Float,
        focal_length: Integer,
        focal_plane_resolution_unit: Integer,
        focal_plane_x_resolution: Float,
        focal_plane_y_resolution: Float,
        interop_offset: Integer,
        iso: Integer,
        metering_mode: Integer,
        scene_capture_type: Integer,
        shutter_speed_value: Float,
        sub_sec_time: String,
        white_balance: Integer
      }

    class ExifDetails < Imagekit::Internal::Type::BaseModel
      attr_reader aperture_value: Float?

      def aperture_value=: (Float) -> Float

      attr_reader color_space: Integer?

      def color_space=: (Integer) -> Integer

      attr_reader create_date: String?

      def create_date=: (String) -> String

      attr_reader custom_rendered: Integer?

      def custom_rendered=: (Integer) -> Integer

      attr_reader date_time_original: String?

      def date_time_original=: (String) -> String

      attr_reader exif_image_height: Integer?

      def exif_image_height=: (Integer) -> Integer

      attr_reader exif_image_width: Integer?

      def exif_image_width=: (Integer) -> Integer

      attr_reader exif_version: String?

      def exif_version=: (String) -> String

      attr_reader exposure_compensation: Float?

      def exposure_compensation=: (Float) -> Float

      attr_reader exposure_mode: Integer?

      def exposure_mode=: (Integer) -> Integer

      attr_reader exposure_program: Integer?

      def exposure_program=: (Integer) -> Integer

      attr_reader exposure_time: Float?

      def exposure_time=: (Float) -> Float

      attr_reader flash: Integer?

      def flash=: (Integer) -> Integer

      attr_reader flashpix_version: String?

      def flashpix_version=: (String) -> String

      attr_reader f_number: Float?

      def f_number=: (Float) -> Float

      attr_reader focal_length: Integer?

      def focal_length=: (Integer) -> Integer

      attr_reader focal_plane_resolution_unit: Integer?

      def focal_plane_resolution_unit=: (Integer) -> Integer

      attr_reader focal_plane_x_resolution: Float?

      def focal_plane_x_resolution=: (Float) -> Float

      attr_reader focal_plane_y_resolution: Float?

      def focal_plane_y_resolution=: (Float) -> Float

      attr_reader interop_offset: Integer?

      def interop_offset=: (Integer) -> Integer

      attr_reader iso: Integer?

      def iso=: (Integer) -> Integer

      attr_reader metering_mode: Integer?

      def metering_mode=: (Integer) -> Integer

      attr_reader scene_capture_type: Integer?

      def scene_capture_type=: (Integer) -> Integer

      attr_reader shutter_speed_value: Float?

      def shutter_speed_value=: (Float) -> Float

      attr_reader sub_sec_time: String?

      def sub_sec_time=: (String) -> String

      attr_reader white_balance: Integer?

      def white_balance=: (Integer) -> Integer

      def initialize: (
        ?aperture_value: Float,
        ?color_space: Integer,
        ?create_date: String,
        ?custom_rendered: Integer,
        ?date_time_original: String,
        ?exif_image_height: Integer,
        ?exif_image_width: Integer,
        ?exif_version: String,
        ?exposure_compensation: Float,
        ?exposure_mode: Integer,
        ?exposure_program: Integer,
        ?exposure_time: Float,
        ?flash: Integer,
        ?flashpix_version: String,
        ?f_number: Float,
        ?focal_length: Integer,
        ?focal_plane_resolution_unit: Integer,
        ?focal_plane_x_resolution: Float,
        ?focal_plane_y_resolution: Float,
        ?interop_offset: Integer,
        ?iso: Integer,
        ?metering_mode: Integer,
        ?scene_capture_type: Integer,
        ?shutter_speed_value: Float,
        ?sub_sec_time: String,
        ?white_balance: Integer
      ) -> void

      def to_hash: -> {
        aperture_value: Float,
        color_space: Integer,
        create_date: String,
        custom_rendered: Integer,
        date_time_original: String,
        exif_image_height: Integer,
        exif_image_width: Integer,
        exif_version: String,
        exposure_compensation: Float,
        exposure_mode: Integer,
        exposure_program: Integer,
        exposure_time: Float,
        flash: Integer,
        flashpix_version: String,
        f_number: Float,
        focal_length: Integer,
        focal_plane_resolution_unit: Integer,
        focal_plane_x_resolution: Float,
        focal_plane_y_resolution: Float,
        interop_offset: Integer,
        iso: Integer,
        metering_mode: Integer,
        scene_capture_type: Integer,
        shutter_speed_value: Float,
        sub_sec_time: String,
        white_balance: Integer
      }
    end
  end
end
