module Imagekit
  module Models
    type file_get_response =
      {
        ai_tags: ::Array[Imagekit::Models::FileGetResponse::AITag]?,
        created_at: String,
        custom_coordinates: String?,
        custom_metadata: top,
        file_id: String,
        file_path: String,
        file_type: String,
        has_alpha: bool,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        mime: String,
        name: String,
        size: Float,
        tags: ::Array[String]?,
        thumbnail: String,
        type: String,
        updated_at: String,
        url: String,
        version_info: Imagekit::Models::FileGetResponse::VersionInfo,
        width: Float
      }

    class FileGetResponse < Imagekit::Internal::Type::BaseModel
      attr_accessor ai_tags: ::Array[Imagekit::Models::FileGetResponse::AITag]?

      attr_reader created_at: String?

      def created_at=: (String) -> String

      attr_accessor custom_coordinates: String?

      attr_reader custom_metadata: top?

      def custom_metadata=: (top) -> top

      attr_reader file_id: String?

      def file_id=: (String) -> String

      attr_reader file_path: String?

      def file_path=: (String) -> String

      attr_reader file_type: String?

      def file_type=: (String) -> String

      attr_reader has_alpha: bool?

      def has_alpha=: (bool) -> bool

      attr_reader height: Float?

      def height=: (Float) -> Float

      attr_reader is_private_file: bool?

      def is_private_file=: (bool) -> bool

      attr_reader is_published: bool?

      def is_published=: (bool) -> bool

      attr_reader mime: String?

      def mime=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader size: Float?

      def size=: (Float) -> Float

      attr_accessor tags: ::Array[String]?

      attr_reader thumbnail: String?

      def thumbnail=: (String) -> String

      attr_reader type: String?

      def type=: (String) -> String

      attr_reader updated_at: String?

      def updated_at=: (String) -> String

      attr_reader url: String?

      def url=: (String) -> String

      attr_reader version_info: Imagekit::Models::FileGetResponse::VersionInfo?

      def version_info=: (
        Imagekit::Models::FileGetResponse::VersionInfo
      ) -> Imagekit::Models::FileGetResponse::VersionInfo

      attr_reader width: Float?

      def width=: (Float) -> Float

      def initialize: (
        ?ai_tags: ::Array[Imagekit::Models::FileGetResponse::AITag]?,
        ?created_at: String,
        ?custom_coordinates: String?,
        ?custom_metadata: top,
        ?file_id: String,
        ?file_path: String,
        ?file_type: String,
        ?has_alpha: bool,
        ?height: Float,
        ?is_private_file: bool,
        ?is_published: bool,
        ?mime: String,
        ?name: String,
        ?size: Float,
        ?tags: ::Array[String]?,
        ?thumbnail: String,
        ?type: String,
        ?updated_at: String,
        ?url: String,
        ?version_info: Imagekit::Models::FileGetResponse::VersionInfo,
        ?width: Float
      ) -> void

      def to_hash: -> {
        ai_tags: ::Array[Imagekit::Models::FileGetResponse::AITag]?,
        created_at: String,
        custom_coordinates: String?,
        custom_metadata: top,
        file_id: String,
        file_path: String,
        file_type: String,
        has_alpha: bool,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        mime: String,
        name: String,
        size: Float,
        tags: ::Array[String]?,
        thumbnail: String,
        type: String,
        updated_at: String,
        url: String,
        version_info: Imagekit::Models::FileGetResponse::VersionInfo,
        width: Float
      }

      type ai_tag = { confidence: Float, name: String, source: String }

      class AITag < Imagekit::Internal::Type::BaseModel
        attr_reader confidence: Float?

        def confidence=: (Float) -> Float

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader source: String?

        def source=: (String) -> String

        def initialize: (
          ?confidence: Float,
          ?name: String,
          ?source: String
        ) -> void

        def to_hash: -> { confidence: Float, name: String, source: String }
      end

      type version_info = { id: String, name: String }

      class VersionInfo < Imagekit::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (?id: String, ?name: String) -> void

        def to_hash: -> { id: String, name: String }
      end
    end
  end
end
