module Imagekit
  module Models
    type file_upload_v1_params =
      {
        file: String,
        file_name: String,
        token: String,
        checks: String,
        custom_coordinates: String,
        custom_metadata: String,
        expire: String,
        extensions: String,
        folder: String,
        is_private_file: Imagekit::Models::FileUploadV1Params::is_private_file,
        is_published: Imagekit::Models::FileUploadV1Params::is_published,
        overwrite_ai_tags: Imagekit::Models::FileUploadV1Params::overwrite_ai_tags,
        overwrite_custom_metadata: Imagekit::Models::FileUploadV1Params::overwrite_custom_metadata,
        overwrite_file: String,
        overwrite_tags: Imagekit::Models::FileUploadV1Params::overwrite_tags,
        public_key: String,
        response_fields: String,
        signature: String,
        tags: String,
        transformation: String,
        use_unique_file_name: Imagekit::Models::FileUploadV1Params::use_unique_file_name,
        webhook_url: String
      }
      & Imagekit::Internal::Type::request_parameters

    class FileUploadV1Params < Imagekit::Internal::Type::BaseModel
      extend Imagekit::Internal::Type::RequestParameters::Converter
      include Imagekit::Internal::Type::RequestParameters

      attr_accessor file: String

      attr_accessor file_name: String

      attr_reader token: String?

      def token=: (String) -> String

      attr_reader checks: String?

      def checks=: (String) -> String

      attr_reader custom_coordinates: String?

      def custom_coordinates=: (String) -> String

      attr_reader custom_metadata: String?

      def custom_metadata=: (String) -> String

      attr_reader expire: String?

      def expire=: (String) -> String

      attr_reader extensions: String?

      def extensions=: (String) -> String

      attr_reader folder: String?

      def folder=: (String) -> String

      attr_reader is_private_file: Imagekit::Models::FileUploadV1Params::is_private_file?

      def is_private_file=: (
        Imagekit::Models::FileUploadV1Params::is_private_file
      ) -> Imagekit::Models::FileUploadV1Params::is_private_file

      attr_reader is_published: Imagekit::Models::FileUploadV1Params::is_published?

      def is_published=: (
        Imagekit::Models::FileUploadV1Params::is_published
      ) -> Imagekit::Models::FileUploadV1Params::is_published

      attr_reader overwrite_ai_tags: Imagekit::Models::FileUploadV1Params::overwrite_ai_tags?

      def overwrite_ai_tags=: (
        Imagekit::Models::FileUploadV1Params::overwrite_ai_tags
      ) -> Imagekit::Models::FileUploadV1Params::overwrite_ai_tags

      attr_reader overwrite_custom_metadata: Imagekit::Models::FileUploadV1Params::overwrite_custom_metadata?

      def overwrite_custom_metadata=: (
        Imagekit::Models::FileUploadV1Params::overwrite_custom_metadata
      ) -> Imagekit::Models::FileUploadV1Params::overwrite_custom_metadata

      attr_reader overwrite_file: String?

      def overwrite_file=: (String) -> String

      attr_reader overwrite_tags: Imagekit::Models::FileUploadV1Params::overwrite_tags?

      def overwrite_tags=: (
        Imagekit::Models::FileUploadV1Params::overwrite_tags
      ) -> Imagekit::Models::FileUploadV1Params::overwrite_tags

      attr_reader public_key: String?

      def public_key=: (String) -> String

      attr_reader response_fields: String?

      def response_fields=: (String) -> String

      attr_reader signature: String?

      def signature=: (String) -> String

      attr_reader tags: String?

      def tags=: (String) -> String

      attr_reader transformation: String?

      def transformation=: (String) -> String

      attr_reader use_unique_file_name: Imagekit::Models::FileUploadV1Params::use_unique_file_name?

      def use_unique_file_name=: (
        Imagekit::Models::FileUploadV1Params::use_unique_file_name
      ) -> Imagekit::Models::FileUploadV1Params::use_unique_file_name

      attr_reader webhook_url: String?

      def webhook_url=: (String) -> String

      def initialize: (
        file: String,
        file_name: String,
        ?token: String,
        ?checks: String,
        ?custom_coordinates: String,
        ?custom_metadata: String,
        ?expire: String,
        ?extensions: String,
        ?folder: String,
        ?is_private_file: Imagekit::Models::FileUploadV1Params::is_private_file,
        ?is_published: Imagekit::Models::FileUploadV1Params::is_published,
        ?overwrite_ai_tags: Imagekit::Models::FileUploadV1Params::overwrite_ai_tags,
        ?overwrite_custom_metadata: Imagekit::Models::FileUploadV1Params::overwrite_custom_metadata,
        ?overwrite_file: String,
        ?overwrite_tags: Imagekit::Models::FileUploadV1Params::overwrite_tags,
        ?public_key: String,
        ?response_fields: String,
        ?signature: String,
        ?tags: String,
        ?transformation: String,
        ?use_unique_file_name: Imagekit::Models::FileUploadV1Params::use_unique_file_name,
        ?webhook_url: String,
        ?request_options: Imagekit::request_opts
      ) -> void

      def to_hash: -> {
        file: String,
        file_name: String,
        token: String,
        checks: String,
        custom_coordinates: String,
        custom_metadata: String,
        expire: String,
        extensions: String,
        folder: String,
        is_private_file: Imagekit::Models::FileUploadV1Params::is_private_file,
        is_published: Imagekit::Models::FileUploadV1Params::is_published,
        overwrite_ai_tags: Imagekit::Models::FileUploadV1Params::overwrite_ai_tags,
        overwrite_custom_metadata: Imagekit::Models::FileUploadV1Params::overwrite_custom_metadata,
        overwrite_file: String,
        overwrite_tags: Imagekit::Models::FileUploadV1Params::overwrite_tags,
        public_key: String,
        response_fields: String,
        signature: String,
        tags: String,
        transformation: String,
        use_unique_file_name: Imagekit::Models::FileUploadV1Params::use_unique_file_name,
        webhook_url: String,
        request_options: Imagekit::RequestOptions
      }

      type is_private_file = :true | :false

      module IsPrivateFile
        extend Imagekit::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Imagekit::Models::FileUploadV1Params::is_private_file]
      end

      type is_published = :true | :false

      module IsPublished
        extend Imagekit::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Imagekit::Models::FileUploadV1Params::is_published]
      end

      type overwrite_ai_tags = :true | :false

      module OverwriteAITags
        extend Imagekit::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Imagekit::Models::FileUploadV1Params::overwrite_ai_tags]
      end

      type overwrite_custom_metadata = :true | :false

      module OverwriteCustomMetadata
        extend Imagekit::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Imagekit::Models::FileUploadV1Params::overwrite_custom_metadata]
      end

      type overwrite_tags = :true | :false

      module OverwriteTags
        extend Imagekit::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Imagekit::Models::FileUploadV1Params::overwrite_tags]
      end

      type use_unique_file_name = :true | :false

      module UseUniqueFileName
        extend Imagekit::Internal::Type::Enum

        TRUE: :true
        FALSE: :false

        def self?.values: -> ::Array[Imagekit::Models::FileUploadV1Params::use_unique_file_name]
      end
    end
  end
end
