module Imagekit
  module Models
    type file_upload_response =
      {
        ai_tags: ::Array[Imagekit::Models::FileUploadResponse::AITag]?,
        audio_codec: String,
        bit_rate: Integer,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        duration: Integer,
        embedded_metadata: ::Hash[Symbol, top],
        extension_status: Imagekit::Models::FileUploadResponse::ExtensionStatus,
        file_id: String,
        file_path: String,
        file_type: String,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        metadata: Imagekit::Models::FileUploadResponse::Metadata,
        name: String,
        size: Float,
        tags: ::Array[String]?,
        thumbnail_url: String,
        url: String,
        version_info: Imagekit::Models::FileUploadResponse::VersionInfo,
        video_codec: String,
        width: Float
      }

    class FileUploadResponse < Imagekit::Internal::Type::BaseModel
      attr_accessor ai_tags: ::Array[Imagekit::Models::FileUploadResponse::AITag]?

      attr_reader audio_codec: String?

      def audio_codec=: (String) -> String

      attr_reader bit_rate: Integer?

      def bit_rate=: (Integer) -> Integer

      attr_accessor custom_coordinates: String?

      attr_reader custom_metadata: ::Hash[Symbol, top]?

      def custom_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader duration: Integer?

      def duration=: (Integer) -> Integer

      attr_reader embedded_metadata: ::Hash[Symbol, top]?

      def embedded_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader extension_status: Imagekit::Models::FileUploadResponse::ExtensionStatus?

      def extension_status=: (
        Imagekit::Models::FileUploadResponse::ExtensionStatus
      ) -> Imagekit::Models::FileUploadResponse::ExtensionStatus

      attr_reader file_id: String?

      def file_id=: (String) -> String

      attr_reader file_path: String?

      def file_path=: (String) -> String

      attr_reader file_type: String?

      def file_type=: (String) -> String

      attr_reader height: Float?

      def height=: (Float) -> Float

      attr_reader is_private_file: bool?

      def is_private_file=: (bool) -> bool

      attr_reader is_published: bool?

      def is_published=: (bool) -> bool

      attr_reader metadata: Imagekit::Models::FileUploadResponse::Metadata?

      def metadata=: (
        Imagekit::Models::FileUploadResponse::Metadata
      ) -> Imagekit::Models::FileUploadResponse::Metadata

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader size: Float?

      def size=: (Float) -> Float

      attr_accessor tags: ::Array[String]?

      attr_reader thumbnail_url: String?

      def thumbnail_url=: (String) -> String

      attr_reader url: String?

      def url=: (String) -> String

      attr_reader version_info: Imagekit::Models::FileUploadResponse::VersionInfo?

      def version_info=: (
        Imagekit::Models::FileUploadResponse::VersionInfo
      ) -> Imagekit::Models::FileUploadResponse::VersionInfo

      attr_reader video_codec: String?

      def video_codec=: (String) -> String

      attr_reader width: Float?

      def width=: (Float) -> Float

      def initialize: (
        ?ai_tags: ::Array[Imagekit::Models::FileUploadResponse::AITag]?,
        ?audio_codec: String,
        ?bit_rate: Integer,
        ?custom_coordinates: String?,
        ?custom_metadata: ::Hash[Symbol, top],
        ?duration: Integer,
        ?embedded_metadata: ::Hash[Symbol, top],
        ?extension_status: Imagekit::Models::FileUploadResponse::ExtensionStatus,
        ?file_id: String,
        ?file_path: String,
        ?file_type: String,
        ?height: Float,
        ?is_private_file: bool,
        ?is_published: bool,
        ?metadata: Imagekit::Models::FileUploadResponse::Metadata,
        ?name: String,
        ?size: Float,
        ?tags: ::Array[String]?,
        ?thumbnail_url: String,
        ?url: String,
        ?version_info: Imagekit::Models::FileUploadResponse::VersionInfo,
        ?video_codec: String,
        ?width: Float
      ) -> void

      def to_hash: -> {
        ai_tags: ::Array[Imagekit::Models::FileUploadResponse::AITag]?,
        audio_codec: String,
        bit_rate: Integer,
        custom_coordinates: String?,
        custom_metadata: ::Hash[Symbol, top],
        duration: Integer,
        embedded_metadata: ::Hash[Symbol, top],
        extension_status: Imagekit::Models::FileUploadResponse::ExtensionStatus,
        file_id: String,
        file_path: String,
        file_type: String,
        height: Float,
        is_private_file: bool,
        is_published: bool,
        metadata: Imagekit::Models::FileUploadResponse::Metadata,
        name: String,
        size: Float,
        tags: ::Array[String]?,
        thumbnail_url: String,
        url: String,
        version_info: Imagekit::Models::FileUploadResponse::VersionInfo,
        video_codec: String,
        width: Float
      }

      type ai_tag = { confidence: Float, name: String, source: String }

      class AITag < Imagekit::Internal::Type::BaseModel
        attr_reader confidence: Float?

        def confidence=: (Float) -> Float

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader source: String?

        def source=: (String) -> String

        def initialize: (
          ?confidence: Float,
          ?name: String,
          ?source: String
        ) -> void

        def to_hash: -> { confidence: Float, name: String, source: String }
      end

      type extension_status =
        {
          aws_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging,
          google_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging,
          remove_bg: Imagekit::Models::FileUploadResponse::ExtensionStatus::remove_bg
        }

      class ExtensionStatus < Imagekit::Internal::Type::BaseModel
        attr_reader aws_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging?

        def aws_auto_tagging=: (
          Imagekit::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging
        ) -> Imagekit::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging

        attr_reader google_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging?

        def google_auto_tagging=: (
          Imagekit::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging
        ) -> Imagekit::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging

        attr_reader remove_bg: Imagekit::Models::FileUploadResponse::ExtensionStatus::remove_bg?

        def remove_bg=: (
          Imagekit::Models::FileUploadResponse::ExtensionStatus::remove_bg
        ) -> Imagekit::Models::FileUploadResponse::ExtensionStatus::remove_bg

        def initialize: (
          ?aws_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging,
          ?google_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging,
          ?remove_bg: Imagekit::Models::FileUploadResponse::ExtensionStatus::remove_bg
        ) -> void

        def to_hash: -> {
          aws_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging,
          google_auto_tagging: Imagekit::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging,
          remove_bg: Imagekit::Models::FileUploadResponse::ExtensionStatus::remove_bg
        }

        type aws_auto_tagging = :success | :pending | :failed

        module AwsAutoTagging
          extend Imagekit::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekit::Models::FileUploadResponse::ExtensionStatus::aws_auto_tagging]
        end

        type google_auto_tagging = :success | :pending | :failed

        module GoogleAutoTagging
          extend Imagekit::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekit::Models::FileUploadResponse::ExtensionStatus::google_auto_tagging]
        end

        type remove_bg = :success | :pending | :failed

        module RemoveBg
          extend Imagekit::Internal::Type::Enum

          SUCCESS: :success
          PENDING: :pending
          FAILED: :failed

          def self?.values: -> ::Array[Imagekit::Models::FileUploadResponse::ExtensionStatus::remove_bg]
        end
      end

      type metadata =
        {
          audio_codec: String,
          bit_rate: Integer,
          density: Integer,
          duration: Integer,
          exif: Imagekit::Models::FileUploadResponse::Metadata::Exif,
          format_: String,
          has_color_profile: bool,
          has_transparency: bool,
          height: Integer,
          p_hash: String,
          quality: Integer,
          size: Integer,
          video_codec: String,
          width: Integer
        }

      class Metadata < Imagekit::Internal::Type::BaseModel
        attr_reader audio_codec: String?

        def audio_codec=: (String) -> String

        attr_reader bit_rate: Integer?

        def bit_rate=: (Integer) -> Integer

        attr_reader density: Integer?

        def density=: (Integer) -> Integer

        attr_reader duration: Integer?

        def duration=: (Integer) -> Integer

        attr_reader exif: Imagekit::Models::FileUploadResponse::Metadata::Exif?

        def exif=: (
          Imagekit::Models::FileUploadResponse::Metadata::Exif
        ) -> Imagekit::Models::FileUploadResponse::Metadata::Exif

        attr_reader format_: String?

        def format_=: (String) -> String

        attr_reader has_color_profile: bool?

        def has_color_profile=: (bool) -> bool

        attr_reader has_transparency: bool?

        def has_transparency=: (bool) -> bool

        attr_reader height: Integer?

        def height=: (Integer) -> Integer

        attr_reader p_hash: String?

        def p_hash=: (String) -> String

        attr_reader quality: Integer?

        def quality=: (Integer) -> Integer

        attr_reader size: Integer?

        def size=: (Integer) -> Integer

        attr_reader video_codec: String?

        def video_codec=: (String) -> String

        attr_reader width: Integer?

        def width=: (Integer) -> Integer

        def initialize: (
          ?audio_codec: String,
          ?bit_rate: Integer,
          ?density: Integer,
          ?duration: Integer,
          ?exif: Imagekit::Models::FileUploadResponse::Metadata::Exif,
          ?format_: String,
          ?has_color_profile: bool,
          ?has_transparency: bool,
          ?height: Integer,
          ?p_hash: String,
          ?quality: Integer,
          ?size: Integer,
          ?video_codec: String,
          ?width: Integer
        ) -> void

        def to_hash: -> {
          audio_codec: String,
          bit_rate: Integer,
          density: Integer,
          duration: Integer,
          exif: Imagekit::Models::FileUploadResponse::Metadata::Exif,
          format_: String,
          has_color_profile: bool,
          has_transparency: bool,
          height: Integer,
          p_hash: String,
          quality: Integer,
          size: Integer,
          video_codec: String,
          width: Integer
        }

        type exif =
          {
            exif: Imagekit::ExifDetails,
            gps: Imagekit::Gps,
            image: Imagekit::ExifImage,
            interoperability: Imagekit::Interoperability,
            makernote: ::Hash[Symbol, top],
            thumbnail: Imagekit::Thumbnail
          }

        class Exif < Imagekit::Internal::Type::BaseModel
          attr_reader exif: Imagekit::ExifDetails?

          def exif=: (Imagekit::ExifDetails) -> Imagekit::ExifDetails

          attr_reader gps: Imagekit::Gps?

          def gps=: (Imagekit::Gps) -> Imagekit::Gps

          attr_reader image: Imagekit::ExifImage?

          def image=: (Imagekit::ExifImage) -> Imagekit::ExifImage

          attr_reader interoperability: Imagekit::Interoperability?

          def interoperability=: (
            Imagekit::Interoperability
          ) -> Imagekit::Interoperability

          attr_reader makernote: ::Hash[Symbol, top]?

          def makernote=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader thumbnail: Imagekit::Thumbnail?

          def thumbnail=: (Imagekit::Thumbnail) -> Imagekit::Thumbnail

          def initialize: (
            ?exif: Imagekit::ExifDetails,
            ?gps: Imagekit::Gps,
            ?image: Imagekit::ExifImage,
            ?interoperability: Imagekit::Interoperability,
            ?makernote: ::Hash[Symbol, top],
            ?thumbnail: Imagekit::Thumbnail
          ) -> void

          def to_hash: -> {
            exif: Imagekit::ExifDetails,
            gps: Imagekit::Gps,
            image: Imagekit::ExifImage,
            interoperability: Imagekit::Interoperability,
            makernote: ::Hash[Symbol, top],
            thumbnail: Imagekit::Thumbnail
          }
        end
      end

      type version_info = { id: String, name: String }

      class VersionInfo < Imagekit::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (?id: String, ?name: String) -> void

        def to_hash: -> { id: String, name: String }
      end
    end
  end
end
