module Imagekit
  module Models
    type file_delete_params =
      {  } & Imagekit::Internal::Type::request_parameters

    class FileDeleteParams < Imagekit::Internal::Type::BaseModel
      extend Imagekit::Internal::Type::RequestParameters::Converter
      include Imagekit::Internal::Type::RequestParameters

      def initialize: (?request_options: Imagekit::request_opts) -> void

      def to_hash: -> { request_options: Imagekit::RequestOptions }
    end
  end
end
