module Imagekit
  module Models
    type file_update_params =
      {
        update_file_details_request: Imagekit::Models::update_file_details_request
      }
      & Imagekit::Internal::Type::request_parameters

    class FileUpdateParams < Imagekit::Internal::Type::BaseModel
      extend Imagekit::Internal::Type::RequestParameters::Converter
      include Imagekit::Internal::Type::RequestParameters

      def update_file_details_request: -> Imagekit::Models::update_file_details_request

      def update_file_details_request=: (
        Imagekit::Models::update_file_details_request _
      ) -> Imagekit::Models::update_file_details_request

      def initialize: (
        update_file_details_request: Imagekit::Models::update_file_details_request,
        ?request_options: Imagekit::request_opts
      ) -> void

      def to_hash: -> {
        update_file_details_request: Imagekit::Models::update_file_details_request,
        request_options: Imagekit::RequestOptions
      }
    end
  end
end
