module Imagekit
  module Models
    type gps = { gps_version_id: ::Array[Integer] }

    class Gps < Imagekit::Internal::Type::BaseModel
      attr_reader gps_version_id: ::Array[Integer]?

      def gps_version_id=: (::Array[Integer]) -> ::Array[Integer]

      def initialize: (?gps_version_id: ::Array[Integer]) -> void

      def to_hash: -> { gps_version_id: ::Array[Integer] }
    end
  end
end
