module Imagekit
  module Models
    type interoperability = { interop_index: String, interop_version: String }

    class Interoperability < Imagekit::Internal::Type::BaseModel
      attr_reader interop_index: String?

      def interop_index=: (String) -> String

      attr_reader interop_version: String?

      def interop_version=: (String) -> String

      def initialize: (?interop_index: String, ?interop_version: String) -> void

      def to_hash: -> { interop_index: String, interop_version: String }
    end
  end
end
