module Imagekit
  module Models
    type overlay =
      Imagekit::TextOverlay
      | Imagekit::ImageOverlay
      | Imagekit::VideoOverlay
      | Imagekit::SubtitleOverlay
      | Imagekit::SolidColorOverlay

    module Overlay
      extend Imagekit::Internal::Type::Union

      def self?.variants: -> ::Array[Imagekit::Models::overlay]
    end
  end
end
