module Imagekit
  module Models
    type removedot_bg_extension =
      {
        name: Imagekit::Models::RemovedotBgExtension::name_,
        options: Imagekit::RemovedotBgExtension::Options
      }

    class RemovedotBgExtension < Imagekit::Internal::Type::BaseModel
      attr_accessor name: Imagekit::Models::RemovedotBgExtension::name_

      attr_reader options: Imagekit::RemovedotBgExtension::Options?

      def options=: (
        Imagekit::RemovedotBgExtension::Options
      ) -> Imagekit::RemovedotBgExtension::Options

      def initialize: (
        name: Imagekit::Models::RemovedotBgExtension::name_,
        ?options: Imagekit::RemovedotBgExtension::Options
      ) -> void

      def to_hash: -> {
        name: Imagekit::Models::RemovedotBgExtension::name_,
        options: Imagekit::RemovedotBgExtension::Options
      }

      type name_ = :"remove-bg"

      module Name
        extend Imagekit::Internal::Type::Enum

        REMOVE_BG: :"remove-bg"

        def self?.values: -> ::Array[Imagekit::Models::RemovedotBgExtension::name_]
      end

      type options =
        {
          add_shadow: bool,
          bg_color: String,
          bg_image_url: String,
          semitransparency: bool
        }

      class Options < Imagekit::Internal::Type::BaseModel
        attr_reader add_shadow: bool?

        def add_shadow=: (bool) -> bool

        attr_reader bg_color: String?

        def bg_color=: (String) -> String

        attr_reader bg_image_url: String?

        def bg_image_url=: (String) -> String

        attr_reader semitransparency: bool?

        def semitransparency=: (bool) -> bool

        def initialize: (
          ?add_shadow: bool,
          ?bg_color: String,
          ?bg_image_url: String,
          ?semitransparency: bool
        ) -> void

        def to_hash: -> {
          add_shadow: bool,
          bg_color: String,
          bg_image_url: String,
          semitransparency: bool
        }
      end
    end
  end
end
