module Imagekit
  module Models
    type solid_color_overlay_transformation =
      {
        alpha: Float,
        background: String,
        gradient: Imagekit::Models::SolidColorOverlayTransformation::gradient,
        height: Imagekit::Models::SolidColorOverlayTransformation::height,
        radius: Imagekit::Models::SolidColorOverlayTransformation::radius,
        width: Imagekit::Models::SolidColorOverlayTransformation::width
      }

    class SolidColorOverlayTransformation < Imagekit::Internal::Type::BaseModel
      attr_reader alpha: Float?

      def alpha=: (Float) -> Float

      attr_reader background: String?

      def background=: (String) -> String

      attr_reader gradient: Imagekit::Models::SolidColorOverlayTransformation::gradient?

      def gradient=: (
        Imagekit::Models::SolidColorOverlayTransformation::gradient
      ) -> Imagekit::Models::SolidColorOverlayTransformation::gradient

      attr_reader height: Imagekit::Models::SolidColorOverlayTransformation::height?

      def height=: (
        Imagekit::Models::SolidColorOverlayTransformation::height
      ) -> Imagekit::Models::SolidColorOverlayTransformation::height

      attr_reader radius: Imagekit::Models::SolidColorOverlayTransformation::radius?

      def radius=: (
        Imagekit::Models::SolidColorOverlayTransformation::radius
      ) -> Imagekit::Models::SolidColorOverlayTransformation::radius

      attr_reader width: Imagekit::Models::SolidColorOverlayTransformation::width?

      def width=: (
        Imagekit::Models::SolidColorOverlayTransformation::width
      ) -> Imagekit::Models::SolidColorOverlayTransformation::width

      def initialize: (
        ?alpha: Float,
        ?background: String,
        ?gradient: Imagekit::Models::SolidColorOverlayTransformation::gradient,
        ?height: Imagekit::Models::SolidColorOverlayTransformation::height,
        ?radius: Imagekit::Models::SolidColorOverlayTransformation::radius,
        ?width: Imagekit::Models::SolidColorOverlayTransformation::width
      ) -> void

      def to_hash: -> {
        alpha: Float,
        background: String,
        gradient: Imagekit::Models::SolidColorOverlayTransformation::gradient,
        height: Imagekit::Models::SolidColorOverlayTransformation::height,
        radius: Imagekit::Models::SolidColorOverlayTransformation::radius,
        width: Imagekit::Models::SolidColorOverlayTransformation::width
      }

      type gradient = true | String

      module Gradient
        extend Imagekit::Internal::Type::Union

        def self?.variants: -> ::Array[Imagekit::Models::SolidColorOverlayTransformation::gradient]
      end

      type height = Float | String

      module Height
        extend Imagekit::Internal::Type::Union

        def self?.variants: -> ::Array[Imagekit::Models::SolidColorOverlayTransformation::height]
      end

      type radius = Float | :max

      module Radius
        extend Imagekit::Internal::Type::Union

        def self?.variants: -> ::Array[Imagekit::Models::SolidColorOverlayTransformation::radius]
      end

      type width = Float | String

      module Width
        extend Imagekit::Internal::Type::Union

        def self?.variants: -> ::Array[Imagekit::Models::SolidColorOverlayTransformation::width]
      end
    end
  end
end
