module Imagekit
  module Models
    type text_overlay =
      {
        text: String,
        type: :text,
        encoding: Imagekit::Models::TextOverlay::encoding,
        transformation: ::Array[Imagekit::TextOverlayTransformation]
      }

    class TextOverlay < Imagekit::Models::BaseOverlay
      def text: -> String

      def text=: (String _) -> String

      def `type`: -> :text

      def type=: (:text _) -> :text

      def encoding: -> Imagekit::Models::TextOverlay::encoding?

      def encoding=: (
        Imagekit::Models::TextOverlay::encoding _
      ) -> Imagekit::Models::TextOverlay::encoding

      def transformation: -> ::Array[Imagekit::TextOverlayTransformation]?

      def transformation=: (
        ::Array[Imagekit::TextOverlayTransformation] _
      ) -> ::Array[Imagekit::TextOverlayTransformation]

      def initialize: (
        text: String,
        ?encoding: Imagekit::Models::TextOverlay::encoding,
        ?transformation: ::Array[Imagekit::TextOverlayTransformation],
        ?type: :text
      ) -> void

      def to_hash: -> {
        text: String,
        type: :text,
        encoding: Imagekit::Models::TextOverlay::encoding,
        transformation: ::Array[Imagekit::TextOverlayTransformation]
      }

      type encoding = :auto | :plain | :base64

      module Encoding
        extend Imagekit::Internal::Type::Enum

        AUTO: :auto
        PLAIN: :plain
        BASE64: :base64

        def self?.values: -> ::Array[Imagekit::Models::TextOverlay::encoding]
      end
    end
  end
end
