module Imagekit
  module Models
    type unwrap_webhook_event =
      Imagekit::VideoTransformationAcceptedEvent
      | Imagekit::VideoTransformationReadyEvent
      | Imagekit::VideoTransformationErrorEvent
      | Imagekit::UploadPreTransformSuccessEvent
      | Imagekit::UploadPreTransformErrorEvent
      | Imagekit::UploadPostTransformSuccessEvent
      | Imagekit::UploadPostTransformErrorEvent

    module UnwrapWebhookEvent
      extend Imagekit::Internal::Type::Union

      def self?.variants: -> ::Array[Imagekit::Models::unwrap_webhook_event]
    end
  end
end
