module Imagekit
  module Models
    type update_file_request =
      Imagekit::UpdateFileRequest::UpdateFileDetails
      | Imagekit::UpdateFileRequest::ChangePublicationStatus

    module UpdateFileRequest
      extend Imagekit::Internal::Type::Union

      type update_file_details =
        {
          custom_coordinates: String?,
          custom_metadata: ::Hash[Symbol, top],
          description: String,
          extensions: Imagekit::Models::extensions,
          remove_ai_tags: Imagekit::Models::UpdateFileRequest::UpdateFileDetails::remove_ai_tags,
          tags: ::Array[String]?,
          webhook_url: String
        }

      class UpdateFileDetails < Imagekit::Internal::Type::BaseModel
        attr_accessor custom_coordinates: String?

        attr_reader custom_metadata: ::Hash[Symbol, top]?

        def custom_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader extensions: Imagekit::Models::extensions?

        def extensions=: (
          Imagekit::Models::extensions
        ) -> Imagekit::Models::extensions

        attr_reader remove_ai_tags: Imagekit::Models::UpdateFileRequest::UpdateFileDetails::remove_ai_tags?

        def remove_ai_tags=: (
          Imagekit::Models::UpdateFileRequest::UpdateFileDetails::remove_ai_tags
        ) -> Imagekit::Models::UpdateFileRequest::UpdateFileDetails::remove_ai_tags

        attr_accessor tags: ::Array[String]?

        attr_reader webhook_url: String?

        def webhook_url=: (String) -> String

        def initialize: (
          ?custom_coordinates: String?,
          ?custom_metadata: ::Hash[Symbol, top],
          ?description: String,
          ?extensions: Imagekit::Models::extensions,
          ?remove_ai_tags: Imagekit::Models::UpdateFileRequest::UpdateFileDetails::remove_ai_tags,
          ?tags: ::Array[String]?,
          ?webhook_url: String
        ) -> void

        def to_hash: -> {
          custom_coordinates: String?,
          custom_metadata: ::Hash[Symbol, top],
          description: String,
          extensions: Imagekit::Models::extensions,
          remove_ai_tags: Imagekit::Models::UpdateFileRequest::UpdateFileDetails::remove_ai_tags,
          tags: ::Array[String]?,
          webhook_url: String
        }

        type remove_ai_tags = ::Array[String] | :all

        module RemoveAITags
          extend Imagekit::Internal::Type::Union

          def self?.variants: -> ::Array[Imagekit::Models::UpdateFileRequest::UpdateFileDetails::remove_ai_tags]

          StringArray: Imagekit::Internal::Type::Converter
        end
      end

      type change_publication_status =
        {
          publish: Imagekit::UpdateFileRequest::ChangePublicationStatus::Publish
        }

      class ChangePublicationStatus < Imagekit::Internal::Type::BaseModel
        attr_reader publish: Imagekit::UpdateFileRequest::ChangePublicationStatus::Publish?

        def publish=: (
          Imagekit::UpdateFileRequest::ChangePublicationStatus::Publish
        ) -> Imagekit::UpdateFileRequest::ChangePublicationStatus::Publish

        def initialize: (
          ?publish: Imagekit::UpdateFileRequest::ChangePublicationStatus::Publish
        ) -> void

        def to_hash: -> {
          publish: Imagekit::UpdateFileRequest::ChangePublicationStatus::Publish
        }

        type publish = { is_published: bool, include_file_versions: bool }

        class Publish < Imagekit::Internal::Type::BaseModel
          attr_accessor is_published: bool

          attr_reader include_file_versions: bool?

          def include_file_versions=: (bool) -> bool

          def initialize: (
            is_published: bool,
            ?include_file_versions: bool
          ) -> void

          def to_hash: -> { is_published: bool, include_file_versions: bool }
        end
      end

      def self?.variants: -> ::Array[Imagekit::Models::update_file_request]
    end
  end
end
