module Imagekit
  module Models
    type upload_pre_transform_error_webhook_event =
      {
        id: String,
        created_at: Time,
        data: Imagekit::UploadPreTransformErrorWebhookEvent::Data,
        request: Imagekit::UploadPreTransformErrorWebhookEvent::Request,
        type: :"upload.pre-transform.error"
      }

    class UploadPreTransformErrorWebhookEvent < Imagekit::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Time

      attr_accessor data: Imagekit::UploadPreTransformErrorWebhookEvent::Data

      attr_accessor request: Imagekit::UploadPreTransformErrorWebhookEvent::Request

      attr_accessor type: :"upload.pre-transform.error"

      def initialize: (
        id: String,
        created_at: Time,
        data: Imagekit::UploadPreTransformErrorWebhookEvent::Data,
        request: Imagekit::UploadPreTransformErrorWebhookEvent::Request,
        ?type: :"upload.pre-transform.error"
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Time,
        data: Imagekit::UploadPreTransformErrorWebhookEvent::Data,
        request: Imagekit::UploadPreTransformErrorWebhookEvent::Request,
        type: :"upload.pre-transform.error"
      }

      type data =
        {
          name: String,
          path: String,
          transformation: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation
        }

      class Data < Imagekit::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor path: String

        attr_accessor transformation: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation

        def initialize: (
          name: String,
          path: String,
          transformation: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation
        ) -> void

        def to_hash: -> {
          name: String,
          path: String,
          transformation: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation
        }

        type transformation =
          {
            error: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation::Error
          }

        class Transformation < Imagekit::Internal::Type::BaseModel
          attr_accessor error: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation::Error

          def initialize: (
            error: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation::Error
          ) -> void

          def to_hash: -> {
            error: Imagekit::UploadPreTransformErrorWebhookEvent::Data::Transformation::Error
          }

          type error = { reason: String }

          class Error < Imagekit::Internal::Type::BaseModel
            attr_accessor reason: String

            def initialize: (reason: String) -> void

            def to_hash: -> { reason: String }
          end
        end
      end

      type request = { transformation: String, x_request_id: String }

      class Request < Imagekit::Internal::Type::BaseModel
        attr_accessor transformation: String

        attr_accessor x_request_id: String

        def initialize: (transformation: String, x_request_id: String) -> void

        def to_hash: -> { transformation: String, x_request_id: String }
      end
    end
  end
end
