module Imagekit
  module Models
    type upload_pre_transform_error_event =
      {
        created_at: Time,
        data: Imagekit::UploadPreTransformErrorEvent::Data,
        request: Imagekit::UploadPreTransformErrorEvent::Request,
        type: :"upload.pre-transform.error"
      }

    class UploadPreTransformErrorEvent < Imagekit::Models::BaseWebhookEvent
      def created_at: -> Time

      def created_at=: (Time _) -> Time

      def data: -> Imagekit::UploadPreTransformErrorEvent::Data

      def data=: (
        Imagekit::UploadPreTransformErrorEvent::Data _
      ) -> Imagekit::UploadPreTransformErrorEvent::Data

      def request: -> Imagekit::UploadPreTransformErrorEvent::Request

      def request=: (
        Imagekit::UploadPreTransformErrorEvent::Request _
      ) -> Imagekit::UploadPreTransformErrorEvent::Request

      def `type`: -> :"upload.pre-transform.error"

      def type=: (
        :"upload.pre-transform.error" _
      ) -> :"upload.pre-transform.error"

      def initialize: (
        created_at: Time,
        data: Imagekit::UploadPreTransformErrorEvent::Data,
        request: Imagekit::UploadPreTransformErrorEvent::Request,
        ?type: :"upload.pre-transform.error"
      ) -> void

      def to_hash: -> {
        created_at: Time,
        data: Imagekit::UploadPreTransformErrorEvent::Data,
        request: Imagekit::UploadPreTransformErrorEvent::Request,
        type: :"upload.pre-transform.error"
      }

      type data =
        {
          name: String,
          path: String,
          transformation: Imagekit::UploadPreTransformErrorEvent::Data::Transformation
        }

      class Data < Imagekit::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor path: String

        attr_accessor transformation: Imagekit::UploadPreTransformErrorEvent::Data::Transformation

        def initialize: (
          name: String,
          path: String,
          transformation: Imagekit::UploadPreTransformErrorEvent::Data::Transformation
        ) -> void

        def to_hash: -> {
          name: String,
          path: String,
          transformation: Imagekit::UploadPreTransformErrorEvent::Data::Transformation
        }

        type transformation =
          {
            error: Imagekit::UploadPreTransformErrorEvent::Data::Transformation::Error
          }

        class Transformation < Imagekit::Internal::Type::BaseModel
          attr_accessor error: Imagekit::UploadPreTransformErrorEvent::Data::Transformation::Error

          def initialize: (
            error: Imagekit::UploadPreTransformErrorEvent::Data::Transformation::Error
          ) -> void

          def to_hash: -> {
            error: Imagekit::UploadPreTransformErrorEvent::Data::Transformation::Error
          }

          type error = { reason: String }

          class Error < Imagekit::Internal::Type::BaseModel
            attr_accessor reason: String

            def initialize: (reason: String) -> void

            def to_hash: -> { reason: String }
          end
        end
      end

      type request = { transformation: String, x_request_id: String }

      class Request < Imagekit::Internal::Type::BaseModel
        attr_accessor transformation: String

        attr_accessor x_request_id: String

        def initialize: (transformation: String, x_request_id: String) -> void

        def to_hash: -> { transformation: String, x_request_id: String }
      end
    end
  end
end
