module Imagekit
  module Models
    type video_overlay =
      {
        input: String,
        type: :video,
        encoding: Imagekit::Models::VideoOverlay::encoding,
        transformation: ::Array[Imagekit::Transformation]
      }

    class VideoOverlay < Imagekit::Models::BaseOverlay
      def input: -> String

      def input=: (String _) -> String

      def `type`: -> :video

      def type=: (:video _) -> :video

      def encoding: -> Imagekit::Models::VideoOverlay::encoding?

      def encoding=: (
        Imagekit::Models::VideoOverlay::encoding _
      ) -> Imagekit::Models::VideoOverlay::encoding

      def transformation: -> ::Array[Imagekit::Transformation]?

      def transformation=: (
        ::Array[Imagekit::Transformation] _
      ) -> ::Array[Imagekit::Transformation]

      def initialize: (
        input: String,
        ?encoding: Imagekit::Models::VideoOverlay::encoding,
        ?transformation: ::Array[Imagekit::Transformation],
        ?type: :video
      ) -> void

      def to_hash: -> {
        input: String,
        type: :video,
        encoding: Imagekit::Models::VideoOverlay::encoding,
        transformation: ::Array[Imagekit::Transformation]
      }

      type encoding = :auto | :plain | :base64

      module Encoding
        extend Imagekit::Internal::Type::Enum

        AUTO: :auto
        PLAIN: :plain
        BASE64: :base64

        def self?.values: -> ::Array[Imagekit::Models::VideoOverlay::encoding]
      end
    end
  end
end
