module Imagekit
  module Resources
    class Accounts
      attr_reader usage: Imagekit::Resources::Accounts::Usage

      attr_reader origins: Imagekit::Resources::Accounts::Origins

      attr_reader url_endpoints: Imagekit::Resources::Accounts::URLEndpoints

      def initialize: (client: Imagekit::Client) -> void
    end
  end
end
