module Imagekit
  module Resources
    class BulkJobs
      def copy_folder: (
        destination_path: String,
        source_folder_path: String,
        ?include_versions: bool,
        ?request_options: Imagekit::request_opts
      ) -> Imagekit::Models::BulkJobCopyFolderResponse

      def move_folder: (
        destination_path: String,
        source_folder_path: String,
        ?request_options: Imagekit::request_opts
      ) -> Imagekit::Models::BulkJobMoveFolderResponse

      def retrieve_status: (
        String job_id,
        ?request_options: Imagekit::request_opts
      ) -> Imagekit::Models::BulkJobRetrieveStatusResponse

      def initialize: (client: Imagekit::Client) -> void
    end
  end
end
