module Imagekit
  module Resources
    class CustomMetadataFields
      def create: (
        label: String,
        name: String,
        schema: Imagekit::CustomMetadataFieldCreateParams::Schema,
        ?request_options: Imagekit::request_opts
      ) -> Imagekit::CustomMetadataField

      def update: (
        String id,
        ?label: String,
        ?schema: Imagekit::CustomMetadataFieldUpdateParams::Schema,
        ?request_options: Imagekit::request_opts
      ) -> Imagekit::CustomMetadataField

      def list: (
        ?include_deleted: bool,
        ?request_options: Imagekit::request_opts
      ) -> Imagekit::Models::custom_metadata_field_list_response

      def delete: (
        String id,
        ?request_options: Imagekit::request_opts
      ) -> Imagekit::Models::CustomMetadataFieldDeleteResponse

      def initialize: (client: Imagekit::Client) -> void
    end
  end
end
