module Imagekit
  module Resources
    class Webhooks
      def unsafe_unwrap: (
        String payload
      ) -> (Imagekit::VideoTransformationAcceptedEvent
      | Imagekit::VideoTransformationReadyEvent
      | Imagekit::VideoTransformationErrorEvent
      | Imagekit::UploadPreTransformSuccessEvent
      | Imagekit::UploadPreTransformErrorEvent
      | Imagekit::UploadPostTransformSuccessEvent
      | Imagekit::UploadPostTransformErrorEvent)

      def unwrap: (
        String payload
      ) -> (Imagekit::VideoTransformationAcceptedEvent
      | Imagekit::VideoTransformationReadyEvent
      | Imagekit::VideoTransformationErrorEvent
      | Imagekit::UploadPreTransformSuccessEvent
      | Imagekit::UploadPreTransformErrorEvent
      | Imagekit::UploadPostTransformSuccessEvent
      | Imagekit::UploadPostTransformErrorEvent)

      def initialize: (client: Imagekit::Client) -> void
    end
  end
end
