module Imagekit
  module Models
    module Beta
      module V2
        type file_upload_params =
          {
            file: Imagekit::Internal::file_input,
            file_name: String,
            token: String,
            checks: String,
            custom_coordinates: String,
            custom_metadata: ::Hash[Symbol, top],
            description: String,
            extensions: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::extension],
            folder: String,
            is_private_file: bool,
            is_published: bool,
            overwrite_ai_tags: bool,
            overwrite_custom_metadata: bool,
            overwrite_file: bool,
            overwrite_tags: bool,
            response_fields: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::response_field],
            tags: ::Array[String],
            transformation: Imagekit::Beta::V2::FileUploadParams::Transformation,
            use_unique_file_name: bool,
            webhook_url: String
          }
          & Imagekit::Internal::Type::request_parameters

        class FileUploadParams < Imagekit::Internal::Type::BaseModel
          extend Imagekit::Internal::Type::RequestParameters::Converter
          include Imagekit::Internal::Type::RequestParameters

          attr_accessor file: Imagekit::Internal::file_input

          attr_accessor file_name: String

          attr_reader token: String?

          def token=: (String) -> String

          attr_reader checks: String?

          def checks=: (String) -> String

          attr_reader custom_coordinates: String?

          def custom_coordinates=: (String) -> String

          attr_reader custom_metadata: ::Hash[Symbol, top]?

          def custom_metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader description: String?

          def description=: (String) -> String

          attr_reader extensions: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::extension]?

          def extensions=: (
            ::Array[Imagekit::Models::Beta::V2::FileUploadParams::extension]
          ) -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::extension]

          attr_reader folder: String?

          def folder=: (String) -> String

          attr_reader is_private_file: bool?

          def is_private_file=: (bool) -> bool

          attr_reader is_published: bool?

          def is_published=: (bool) -> bool

          attr_reader overwrite_ai_tags: bool?

          def overwrite_ai_tags=: (bool) -> bool

          attr_reader overwrite_custom_metadata: bool?

          def overwrite_custom_metadata=: (bool) -> bool

          attr_reader overwrite_file: bool?

          def overwrite_file=: (bool) -> bool

          attr_reader overwrite_tags: bool?

          def overwrite_tags=: (bool) -> bool

          attr_reader response_fields: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::response_field]?

          def response_fields=: (
            ::Array[Imagekit::Models::Beta::V2::FileUploadParams::response_field]
          ) -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::response_field]

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader transformation: Imagekit::Beta::V2::FileUploadParams::Transformation?

          def transformation=: (
            Imagekit::Beta::V2::FileUploadParams::Transformation
          ) -> Imagekit::Beta::V2::FileUploadParams::Transformation

          attr_reader use_unique_file_name: bool?

          def use_unique_file_name=: (bool) -> bool

          attr_reader webhook_url: String?

          def webhook_url=: (String) -> String

          def initialize: (
            file: Imagekit::Internal::file_input,
            file_name: String,
            ?token: String,
            ?checks: String,
            ?custom_coordinates: String,
            ?custom_metadata: ::Hash[Symbol, top],
            ?description: String,
            ?extensions: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::extension],
            ?folder: String,
            ?is_private_file: bool,
            ?is_published: bool,
            ?overwrite_ai_tags: bool,
            ?overwrite_custom_metadata: bool,
            ?overwrite_file: bool,
            ?overwrite_tags: bool,
            ?response_fields: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::response_field],
            ?tags: ::Array[String],
            ?transformation: Imagekit::Beta::V2::FileUploadParams::Transformation,
            ?use_unique_file_name: bool,
            ?webhook_url: String,
            ?request_options: Imagekit::request_opts
          ) -> void

          def to_hash: -> {
            file: Imagekit::Internal::file_input,
            file_name: String,
            token: String,
            checks: String,
            custom_coordinates: String,
            custom_metadata: ::Hash[Symbol, top],
            description: String,
            extensions: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::extension],
            folder: String,
            is_private_file: bool,
            is_published: bool,
            overwrite_ai_tags: bool,
            overwrite_custom_metadata: bool,
            overwrite_file: bool,
            overwrite_tags: bool,
            response_fields: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::response_field],
            tags: ::Array[String],
            transformation: Imagekit::Beta::V2::FileUploadParams::Transformation,
            use_unique_file_name: bool,
            webhook_url: String,
            request_options: Imagekit::RequestOptions
          }

          type extension =
            Imagekit::RemovedotBgExtension
            | Imagekit::AutoTaggingExtension
            | Imagekit::AutoDescriptionExtension

          module Extension
            extend Imagekit::Internal::Type::Union

            def self?.variants: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::extension]
          end

          type response_field =
            :tags
            | :customCoordinates
            | :isPrivateFile
            | :embeddedMetadata
            | :isPublished
            | :customMetadata
            | :metadata

          module ResponseField
            extend Imagekit::Internal::Type::Enum

            TAGS: :tags
            CUSTOM_COORDINATES: :customCoordinates
            IS_PRIVATE_FILE: :isPrivateFile
            EMBEDDED_METADATA: :embeddedMetadata
            IS_PUBLISHED: :isPublished
            CUSTOM_METADATA: :customMetadata
            METADATA: :metadata

            def self?.values: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::response_field]
          end

          type transformation =
            {
              post: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::post],
              pre: String
            }

          class Transformation < Imagekit::Internal::Type::BaseModel
            attr_reader post: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::post]?

            def post=: (
              ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::post]
            ) -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::post]

            attr_reader pre: String?

            def pre=: (String) -> String

            def initialize: (
              ?post: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::post],
              ?pre: String
            ) -> void

            def to_hash: -> {
              post: ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::post],
              pre: String
            }

            type post =
              Imagekit::Beta::V2::FileUploadParams::Transformation::Post::SimplePostTransformation
              | Imagekit::Beta::V2::FileUploadParams::Transformation::Post::ConvertGifToVideo
              | Imagekit::Beta::V2::FileUploadParams::Transformation::Post::GenerateAThumbnail
              | Imagekit::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming

            module Post
              extend Imagekit::Internal::Type::Union

              type simple_post_transformation =
                {
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::SimplePostTransformation::type_,
                  value: String
                }

              class SimplePostTransformation < Imagekit::Internal::Type::BaseModel
                attr_accessor type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::SimplePostTransformation::type_

                attr_accessor value: String

                def initialize: (
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::SimplePostTransformation::type_,
                  value: String
                ) -> void

                def to_hash: -> {
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::SimplePostTransformation::type_,
                  value: String
                }

                type type_ = :transformation

                module Type
                  extend Imagekit::Internal::Type::Enum

                  TRANSFORMATION: :transformation

                  def self?.values: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::SimplePostTransformation::type_]
                end
              end

              type convert_gif_to_video =
                {
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::ConvertGifToVideo::type_,
                  value: String
                }

              class ConvertGifToVideo < Imagekit::Internal::Type::BaseModel
                attr_accessor type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::ConvertGifToVideo::type_

                attr_reader value: String?

                def value=: (String) -> String

                def initialize: (
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::ConvertGifToVideo::type_,
                  ?value: String
                ) -> void

                def to_hash: -> {
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::ConvertGifToVideo::type_,
                  value: String
                }

                type type_ = :"gif-to-video"

                module Type
                  extend Imagekit::Internal::Type::Enum

                  GIF_TO_VIDEO: :"gif-to-video"

                  def self?.values: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::ConvertGifToVideo::type_]
                end
              end

              type generate_a_thumbnail =
                {
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::GenerateAThumbnail::type_,
                  value: String
                }

              class GenerateAThumbnail < Imagekit::Internal::Type::BaseModel
                attr_accessor type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::GenerateAThumbnail::type_

                attr_reader value: String?

                def value=: (String) -> String

                def initialize: (
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::GenerateAThumbnail::type_,
                  ?value: String
                ) -> void

                def to_hash: -> {
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::GenerateAThumbnail::type_,
                  value: String
                }

                type type_ = :thumbnail

                module Type
                  extend Imagekit::Internal::Type::Enum

                  THUMBNAIL: :thumbnail

                  def self?.values: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::GenerateAThumbnail::type_]
                end
              end

              type adaptive_bitrate_streaming =
                {
                  protocol: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::protocol,
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::type_,
                  value: String
                }

              class AdaptiveBitrateStreaming < Imagekit::Internal::Type::BaseModel
                attr_accessor protocol: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::protocol

                attr_accessor type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::type_

                attr_accessor value: String

                def initialize: (
                  protocol: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::protocol,
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::type_,
                  value: String
                ) -> void

                def to_hash: -> {
                  protocol: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::protocol,
                  type: Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::type_,
                  value: String
                }

                type protocol = :hls | :dash

                module Protocol
                  extend Imagekit::Internal::Type::Enum

                  HLS: :hls
                  DASH: :dash

                  def self?.values: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::protocol]
                end

                type type_ = :abs

                module Type
                  extend Imagekit::Internal::Type::Enum

                  ABS: :abs

                  def self?.values: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::Post::AdaptiveBitrateStreaming::type_]
                end
              end

              def self?.variants: -> ::Array[Imagekit::Models::Beta::V2::FileUploadParams::Transformation::post]
            end
          end
        end
      end
    end
  end
end
