# frozen_string_literal: true

module Imagekit
  module Resources
    class Accounts
      class Origins
        # **Note:** This API is currently in beta.
        # Creates a new origin and returns the origin object.
        #
        # @overload create(origin:, request_options: {})
        #
        # @param origin [Imagekit::Models::Accounts::Origin::S3, Imagekit::Models::Accounts::Origin::S3Compatible, Imagekit::Models::Accounts::Origin::CloudinaryBackup, Imagekit::Models::Accounts::Origin::WebFolder, Imagekit::Models::Accounts::Origin::WebProxy, Imagekit::Models::Accounts::Origin::Gcs, Imagekit::Models::Accounts::Origin::AzureBlob, Imagekit::Models::Accounts::Origin::AkeneoPim] Schema for origin resources.
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekit::Models::Accounts::OriginCreateResponse::S3, Imagekit::Models::Accounts::OriginCreateResponse::S3Compatible, Imagekit::Models::Accounts::OriginCreateResponse::CloudinaryBackup, Imagekit::Models::Accounts::OriginCreateResponse::WebFolder, Imagekit::Models::Accounts::OriginCreateResponse::WebProxy, Imagekit::Models::Accounts::OriginCreateResponse::Gcs, Imagekit::Models::Accounts::OriginCreateResponse::AzureBlob, Imagekit::Models::Accounts::OriginCreateResponse::AkeneoPim]
        #
        # @see Imagekit::Models::Accounts::OriginCreateParams
        def create(params)
          parsed, options = Imagekit::Accounts::OriginCreateParams.dump_request(params)
          @client.request(
            method: :post,
            path: "v1/accounts/origins",
            body: parsed[:origin],
            model: Imagekit::Models::Accounts::OriginCreateResponse,
            options: options
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekit::Models::Accounts::OriginUpdateParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Updates the origin identified by `id` and returns the updated origin object.
        #
        # @overload update(id, origin:, request_options: {})
        #
        # @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
        #
        # @param origin [Imagekit::Models::Accounts::Origin::S3, Imagekit::Models::Accounts::Origin::S3Compatible, Imagekit::Models::Accounts::Origin::CloudinaryBackup, Imagekit::Models::Accounts::Origin::WebFolder, Imagekit::Models::Accounts::Origin::WebProxy, Imagekit::Models::Accounts::Origin::Gcs, Imagekit::Models::Accounts::Origin::AzureBlob, Imagekit::Models::Accounts::Origin::AkeneoPim] Schema for origin resources.
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekit::Models::Accounts::OriginUpdateResponse::S3, Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible, Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup, Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder, Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy, Imagekit::Models::Accounts::OriginUpdateResponse::Gcs, Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlob, Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim]
        #
        # @see Imagekit::Models::Accounts::OriginUpdateParams
        def update(id, params)
          parsed, options = Imagekit::Accounts::OriginUpdateParams.dump_request(params)
          @client.request(
            method: :put,
            path: ["v1/accounts/origins/%1$s", id],
            body: parsed[:origin],
            model: Imagekit::Models::Accounts::OriginUpdateResponse,
            options: options
          )
        end

        # **Note:** This API is currently in beta.
        # Returns an array of all configured origins for the current account.
        #
        # @overload list(request_options: {})
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Array<Imagekit::Models::Accounts::OriginListResponseItem::S3, Imagekit::Models::Accounts::OriginListResponseItem::S3Compatible, Imagekit::Models::Accounts::OriginListResponseItem::CloudinaryBackup, Imagekit::Models::Accounts::OriginListResponseItem::WebFolder, Imagekit::Models::Accounts::OriginListResponseItem::WebProxy, Imagekit::Models::Accounts::OriginListResponseItem::Gcs, Imagekit::Models::Accounts::OriginListResponseItem::AzureBlob, Imagekit::Models::Accounts::OriginListResponseItem::AkeneoPim>]
        #
        # @see Imagekit::Models::Accounts::OriginListParams
        def list(params = {})
          @client.request(
            method: :get,
            path: "v1/accounts/origins",
            model: Imagekit::Internal::Type::ArrayOf[union: Imagekit::Models::Accounts::OriginListResponseItem],
            options: params[:request_options]
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekit::Models::Accounts::OriginDeleteParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Permanently removes the origin identified by `id`. If the origin is in use by
        # any URL‑endpoints, the API will return an error.
        #
        # @overload delete(id, request_options: {})
        #
        # @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [nil]
        #
        # @see Imagekit::Models::Accounts::OriginDeleteParams
        def delete(id, params = {})
          @client.request(
            method: :delete,
            path: ["v1/accounts/origins/%1$s", id],
            model: NilClass,
            options: params[:request_options]
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekit::Models::Accounts::OriginGetParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Retrieves the origin identified by `id`.
        #
        # @overload get(id, request_options: {})
        #
        # @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekit::Models::Accounts::OriginGetResponse::S3, Imagekit::Models::Accounts::OriginGetResponse::S3Compatible, Imagekit::Models::Accounts::OriginGetResponse::CloudinaryBackup, Imagekit::Models::Accounts::OriginGetResponse::WebFolder, Imagekit::Models::Accounts::OriginGetResponse::WebProxy, Imagekit::Models::Accounts::OriginGetResponse::Gcs, Imagekit::Models::Accounts::OriginGetResponse::AzureBlob, Imagekit::Models::Accounts::OriginGetResponse::AkeneoPim]
        #
        # @see Imagekit::Models::Accounts::OriginGetParams
        def get(id, params = {})
          @client.request(
            method: :get,
            path: ["v1/accounts/origins/%1$s", id],
            model: Imagekit::Models::Accounts::OriginGetResponse,
            options: params[:request_options]
          )
        end

        # @api private
        #
        # @param client [Imagekit::Client]
        def initialize(client:)
          @client = client
        end
      end
    end
  end
end
