# frozen_string_literal: true

module Imagekit
  module Resources
    class Accounts
      class URLEndpoints
        # Some parameter documentations has been truncated, see
        # {Imagekit::Models::Accounts::URLEndpointCreateParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Creates a new URL‑endpoint and returns the resulting object.
        #
        # @overload create(description:, origins: nil, url_prefix: nil, url_rewriter: nil, request_options: {})
        #
        # @param description [String] Description of the URL endpoint.
        #
        # @param origins [Array<String>] Ordered list of origin IDs to try when the file isn’t in the Media Library; Imag
        #
        # @param url_prefix [String] Path segment appended to your base URL to form the endpoint (letters, digits, an
        #
        # @param url_rewriter [Imagekit::Models::Accounts::URLEndpointCreateParams::URLRewriter::Cloudinary, Imagekit::Models::Accounts::URLEndpointCreateParams::URLRewriter::Imgix, Imagekit::Models::Accounts::URLEndpointCreateParams::URLRewriter::Akamai] Configuration for third-party URL rewriting.
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekit::Models::Accounts::URLEndpointCreateResponse]
        #
        # @see Imagekit::Models::Accounts::URLEndpointCreateParams
        def create(params)
          parsed, options = Imagekit::Accounts::URLEndpointCreateParams.dump_request(params)
          @client.request(
            method: :post,
            path: "v1/accounts/url-endpoints",
            body: parsed,
            model: Imagekit::Models::Accounts::URLEndpointCreateResponse,
            options: options
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekit::Models::Accounts::URLEndpointUpdateParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Updates the URL‑endpoint identified by `id` and returns the updated object.
        #
        # @overload update(id, description:, origins: nil, url_prefix: nil, url_rewriter: nil, request_options: {})
        #
        # @param id [String] Unique identifier for the URL-endpoint. This is generated by ImageKit when you c
        #
        # @param description [String] Description of the URL endpoint.
        #
        # @param origins [Array<String>] Ordered list of origin IDs to try when the file isn’t in the Media Library; Imag
        #
        # @param url_prefix [String] Path segment appended to your base URL to form the endpoint (letters, digits, an
        #
        # @param url_rewriter [Imagekit::Models::Accounts::URLEndpointUpdateParams::URLRewriter::Cloudinary, Imagekit::Models::Accounts::URLEndpointUpdateParams::URLRewriter::Imgix, Imagekit::Models::Accounts::URLEndpointUpdateParams::URLRewriter::Akamai] Configuration for third-party URL rewriting.
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekit::Models::Accounts::URLEndpointUpdateResponse]
        #
        # @see Imagekit::Models::Accounts::URLEndpointUpdateParams
        def update(id, params)
          parsed, options = Imagekit::Accounts::URLEndpointUpdateParams.dump_request(params)
          @client.request(
            method: :put,
            path: ["v1/accounts/url-endpoints/%1$s", id],
            body: parsed,
            model: Imagekit::Models::Accounts::URLEndpointUpdateResponse,
            options: options
          )
        end

        # **Note:** This API is currently in beta.
        # Returns an array of all URL‑endpoints configured including the default
        # URL-endpoint generated by ImageKit during account creation.
        #
        # @overload list(request_options: {})
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Array<Imagekit::Models::Accounts::URLEndpointListResponseItem>]
        #
        # @see Imagekit::Models::Accounts::URLEndpointListParams
        def list(params = {})
          @client.request(
            method: :get,
            path: "v1/accounts/url-endpoints",
            model: Imagekit::Internal::Type::ArrayOf[Imagekit::Models::Accounts::URLEndpointListResponseItem],
            options: params[:request_options]
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekit::Models::Accounts::URLEndpointDeleteParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Deletes the URL‑endpoint identified by `id`. You cannot delete the default
        # URL‑endpoint created by ImageKit during account creation.
        #
        # @overload delete(id, request_options: {})
        #
        # @param id [String] Unique identifier for the URL-endpoint. This is generated by ImageKit when you c
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [nil]
        #
        # @see Imagekit::Models::Accounts::URLEndpointDeleteParams
        def delete(id, params = {})
          @client.request(
            method: :delete,
            path: ["v1/accounts/url-endpoints/%1$s", id],
            model: NilClass,
            options: params[:request_options]
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekit::Models::Accounts::URLEndpointGetParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Retrieves the URL‑endpoint identified by `id`.
        #
        # @overload get(id, request_options: {})
        #
        # @param id [String] Unique identifier for the URL-endpoint. This is generated by ImageKit when you c
        #
        # @param request_options [Imagekit::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekit::Models::Accounts::URLEndpointGetResponse]
        #
        # @see Imagekit::Models::Accounts::URLEndpointGetParams
        def get(id, params = {})
          @client.request(
            method: :get,
            path: ["v1/accounts/url-endpoints/%1$s", id],
            model: Imagekit::Models::Accounts::URLEndpointGetResponse,
            options: params[:request_options]
          )
        end

        # @api private
        #
        # @param client [Imagekit::Client]
        def initialize(client:)
          @client = client
        end
      end
    end
  end
end
