# frozen_string_literal: true

module Imagekit
  module Models
    module Accounts
      # Origin object as returned by the API (sensitive fields removed).
      #
      # @see Imagekit::Resources::Accounts::Origins#update
      module OriginUpdateResponse
        extend Imagekit::Internal::Type::Union

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::S3 }

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible }

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup }

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder }

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy }

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::GoogleCloudStorageGcs }

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlobStorage }

        variant -> { Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim }

        class S3 < Imagekit::Internal::Type::BaseModel
          # @!attribute bucket
          #   S3 bucket name.
          #
          #   @return [String]
          required :bucket, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #   Path prefix inside the bucket.
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::S3::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::S3::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, include_canonical_header:, name:, prefix:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::S3} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String] S3 bucket name.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String] Path prefix inside the bucket.
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::S3::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::S3#type
          module Type
            extend Imagekit::Internal::Type::Enum

            S3 = :S3

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class S3Compatible < Imagekit::Internal::Type::BaseModel
          # @!attribute bucket
          #   S3 bucket name.
          #
          #   @return [String]
          required :bucket, String

          # @!attribute endpoint
          #   Custom S3-compatible endpoint.
          #
          #   @return [String]
          required :endpoint, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #   Path prefix inside the bucket.
          #
          #   @return [String]
          required :prefix, String

          # @!attribute s3_force_path_style
          #   Use path-style S3 URLs?
          #
          #   @return [Boolean]
          required :s3_force_path_style, Imagekit::Internal::Type::Boolean, api_name: :s3ForcePathStyle

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, endpoint:, include_canonical_header:, name:, prefix:, s3_force_path_style:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible} for more
          #   details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String] S3 bucket name.
          #
          #   @param endpoint [String] Custom S3-compatible endpoint.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String] Path prefix inside the bucket.
          #
          #   @param s3_force_path_style [Boolean] Use path-style S3 URLs?
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible#type
          module Type
            extend Imagekit::Internal::Type::Enum

            S3_COMPATIBLE = :S3_COMPATIBLE

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class CloudinaryBackup < Imagekit::Internal::Type::BaseModel
          # @!attribute bucket
          #   S3 bucket name.
          #
          #   @return [String]
          required :bucket, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #   Path prefix inside the bucket.
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, include_canonical_header:, name:, prefix:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup} for more
          #   details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String] S3 bucket name.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String] Path prefix inside the bucket.
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup#type
          module Type
            extend Imagekit::Internal::Type::Enum

            CLOUDINARY_BACKUP = :CLOUDINARY_BACKUP

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class WebFolder < Imagekit::Internal::Type::BaseModel
          # @!attribute base_url
          #   Root URL for the web folder origin.
          #
          #   @return [String]
          required :base_url, String, api_name: :baseUrl

          # @!attribute forward_host_header_to_origin
          #   Forward the Host header to origin?
          #
          #   @return [Boolean]
          required :forward_host_header_to_origin,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :forwardHostHeaderToOrigin

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, base_url:, forward_host_header_to_origin:, include_canonical_header:, name:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param base_url [String] Root URL for the web folder origin.
          #
          #   @param forward_host_header_to_origin [Boolean] Forward the Host header to origin?
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder#type
          module Type
            extend Imagekit::Internal::Type::Enum

            WEB_FOLDER = :WEB_FOLDER

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class WebProxy < Imagekit::Internal::Type::BaseModel
          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, include_canonical_header:, name:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy#type
          module Type
            extend Imagekit::Internal::Type::Enum

            WEB_PROXY = :WEB_PROXY

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class GoogleCloudStorageGcs < Imagekit::Internal::Type::BaseModel
          # @!attribute bucket
          #
          #   @return [String]
          required :bucket, String

          # @!attribute client_email
          #
          #   @return [String]
          required :client_email, String, api_name: :clientEmail

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::GoogleCloudStorageGcs::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::GoogleCloudStorageGcs::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, bucket:, client_email:, include_canonical_header:, name:, prefix:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::GoogleCloudStorageGcs} for
          #   more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param bucket [String]
          #
          #   @param client_email [String]
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String]
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::GoogleCloudStorageGcs::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::GoogleCloudStorageGcs#type
          module Type
            extend Imagekit::Internal::Type::Enum

            GCS = :GCS

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class AzureBlobStorage < Imagekit::Internal::Type::BaseModel
          # @!attribute account_name
          #
          #   @return [String]
          required :account_name, String, api_name: :accountName

          # @!attribute container
          #
          #   @return [String]
          required :container, String

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute prefix
          #
          #   @return [String]
          required :prefix, String

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlobStorage::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlobStorage::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, account_name:, container:, include_canonical_header:, name:, prefix:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlobStorage} for more
          #   details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param account_name [String]
          #
          #   @param container [String]
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param prefix [String]
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlobStorage::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlobStorage#type
          module Type
            extend Imagekit::Internal::Type::Enum

            AZURE_BLOB = :AZURE_BLOB

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class AkeneoPim < Imagekit::Internal::Type::BaseModel
          # @!attribute base_url
          #   Akeneo instance base URL.
          #
          #   @return [String]
          required :base_url, String, api_name: :baseUrl

          # @!attribute include_canonical_header
          #   Whether to send a Canonical header.
          #
          #   @return [Boolean]
          required :include_canonical_header,
                   Imagekit::Internal::Type::Boolean,
                   api_name: :includeCanonicalHeader

          # @!attribute name
          #   Display name of the origin.
          #
          #   @return [String]
          required :name, String

          # @!attribute type
          #
          #   @return [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim::Type]
          required :type, enum: -> { Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim::Type }

          # @!attribute base_url_for_canonical_header
          #   URL used in the Canonical header (if enabled).
          #
          #   @return [String, nil]
          optional :base_url_for_canonical_header, String, api_name: :baseUrlForCanonicalHeader

          response_only do
            # @!attribute id
            #   Unique identifier for the origin. This is generated by ImageKit when you create
            #   a new origin.
            #
            #   @return [String]
            required :id, String
          end

          # @!method initialize(id:, base_url:, include_canonical_header:, name:, type:, base_url_for_canonical_header: nil)
          #   Some parameter documentations has been truncated, see
          #   {Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim} for more details.
          #
          #   @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
          #
          #   @param base_url [String] Akeneo instance base URL.
          #
          #   @param include_canonical_header [Boolean] Whether to send a Canonical header.
          #
          #   @param name [String] Display name of the origin.
          #
          #   @param type [Symbol, Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim::Type]
          #
          #   @param base_url_for_canonical_header [String] URL used in the Canonical header (if enabled).

          # @see Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim#type
          module Type
            extend Imagekit::Internal::Type::Enum

            AKENEO_PIM = :AKENEO_PIM

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        # @!method self.variants
        #   @return [Array(Imagekit::Models::Accounts::OriginUpdateResponse::S3, Imagekit::Models::Accounts::OriginUpdateResponse::S3Compatible, Imagekit::Models::Accounts::OriginUpdateResponse::CloudinaryBackup, Imagekit::Models::Accounts::OriginUpdateResponse::WebFolder, Imagekit::Models::Accounts::OriginUpdateResponse::WebProxy, Imagekit::Models::Accounts::OriginUpdateResponse::GoogleCloudStorageGcs, Imagekit::Models::Accounts::OriginUpdateResponse::AzureBlobStorage, Imagekit::Models::Accounts::OriginUpdateResponse::AkeneoPim)]
      end
    end
  end
end
