# frozen_string_literal: true

module Imagekit
  module Models
    module Accounts
      # @see Imagekit::Resources::Accounts::URLEndpoints#create
      class URLEndpointCreateResponse < Imagekit::Internal::Type::BaseModel
        # @!attribute description
        #   Description of the URL endpoint.
        #
        #   @return [String]
        required :description, String

        # @!attribute origins
        #   Ordered list of origin IDs to try when the file isn’t in the Media Library;
        #   ImageKit checks them in the sequence provided. Origin must be created before it
        #   can be used in a URL endpoint.
        #
        #   @return [Array<String>]
        required :origins, Imagekit::Internal::Type::ArrayOf[String]

        # @!attribute url_prefix
        #   Path segment appended to your base URL to form the endpoint (letters, digits,
        #   and hyphens only — or empty for the default endpoint).
        #
        #   @return [String]
        required :url_prefix, String, api_name: :urlPrefix

        # @!attribute url_rewriter
        #   Configuration for third-party URL rewriting.
        #
        #   @return [Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::CloudinaryURLRewriter, Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::ImgixURLRewriter, Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::AkamaiURLRewriter, nil]
        optional :url_rewriter,
                 union: -> { Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter },
                 api_name: :urlRewriter

        response_only do
          # @!attribute id
          #   Unique identifier for the URL-endpoint. This is generated by ImageKit when you
          #   create a new URL-endpoint. For the default URL-endpoint, this is always
          #   `default`.
          #
          #   @return [String]
          required :id, String
        end

        # @!method initialize(id:, description:, origins:, url_prefix:, url_rewriter: nil)
        #   Some parameter documentations has been truncated, see
        #   {Imagekit::Models::Accounts::URLEndpointCreateResponse} for more details.
        #
        #   URL‑endpoint object as returned by the API.
        #
        #   @param id [String] Unique identifier for the URL-endpoint. This is generated by ImageKit when you c
        #
        #   @param description [String] Description of the URL endpoint.
        #
        #   @param origins [Array<String>] Ordered list of origin IDs to try when the file isn’t in the Media Library; Imag
        #
        #   @param url_prefix [String] Path segment appended to your base URL to form the endpoint (letters, digits, an
        #
        #   @param url_rewriter [Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::CloudinaryURLRewriter, Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::ImgixURLRewriter, Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::AkamaiURLRewriter] Configuration for third-party URL rewriting.

        # Configuration for third-party URL rewriting.
        #
        # @see Imagekit::Models::Accounts::URLEndpointCreateResponse#url_rewriter
        module URLRewriter
          extend Imagekit::Internal::Type::Union

          variant -> { Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::CloudinaryURLRewriter }

          variant -> { Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::ImgixURLRewriter }

          variant -> { Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::AkamaiURLRewriter }

          class CloudinaryURLRewriter < Imagekit::Internal::Type::BaseModel
            # @!attribute preserve_asset_delivery_types
            #   Whether to preserve `<asset_type>/<delivery_type>` in the rewritten URL.
            #
            #   @return [Boolean]
            required :preserve_asset_delivery_types,
                     Imagekit::Internal::Type::Boolean,
                     api_name: :preserveAssetDeliveryTypes

            # @!attribute type
            #
            #   @return [Symbol, :CLOUDINARY]
            required :type, const: :CLOUDINARY

            # @!method initialize(preserve_asset_delivery_types:, type: :CLOUDINARY)
            #   @param preserve_asset_delivery_types [Boolean] Whether to preserve `<asset_type>/<delivery_type>` in the rewritten URL.
            #
            #   @param type [Symbol, :CLOUDINARY]
          end

          class ImgixURLRewriter < Imagekit::Internal::Type::BaseModel
            # @!attribute type
            #
            #   @return [Symbol, :IMGIX]
            required :type, const: :IMGIX

            # @!method initialize(type: :IMGIX)
            #   @param type [Symbol, :IMGIX]
          end

          class AkamaiURLRewriter < Imagekit::Internal::Type::BaseModel
            # @!attribute type
            #
            #   @return [Symbol, :AKAMAI]
            required :type, const: :AKAMAI

            # @!method initialize(type: :AKAMAI)
            #   @param type [Symbol, :AKAMAI]
          end

          # @!method self.variants
          #   @return [Array(Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::CloudinaryURLRewriter, Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::ImgixURLRewriter, Imagekit::Models::Accounts::URLEndpointCreateResponse::URLRewriter::AkamaiURLRewriter)]
        end
      end
    end
  end
end
