# typed: strong

module Imagekitio
  module Models
    module Accounts
      class Webhook < Imagekitio::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(Imagekitio::Accounts::Webhook, Imagekitio::Internal::AnyHash)
          end

        # Unique identifier for a webhook.
        sig { returns(String) }
        attr_accessor :id

        # ISO 8601 timestamp of when the webhook was created.
        sig { returns(Time) }
        attr_accessor :created_at

        # Whether the webhook is enabled. When `false`, ImageKit doesn't send any events
        # to the `endpoint`.
        sig { returns(T::Boolean) }
        attr_accessor :enabled

        # The URL where ImageKit sends webhook events as `POST` requests. Must use the
        # `http` or `https` protocol, and must be unique across all webhooks for your
        # account.
        sig { returns(String) }
        attr_accessor :endpoint

        # The event types this webhook is subscribed to. ImageKit sends a request to the
        # `endpoint` only for these events.
        sig do
          returns(
            T::Array[Imagekitio::Accounts::WebhookEventType::TaggedSymbol]
          )
        end
        attr_accessor :events

        # Signing secret generated by ImageKit, used to verify that webhook requests come
        # from ImageKit. Starts with `whsec_`. This value can't be set or changed through
        # the API. Learn more about
        # [verifying webhook signatures](https://imagekit.io/docs/webhooks#verify-webhook-signature).
        sig { returns(String) }
        attr_accessor :secret

        # ISO 8601 timestamp of when the webhook was last updated.
        sig { returns(Time) }
        attr_accessor :updated_at

        # A webhook is an HTTP endpoint that ImageKit notifies when subscribed events
        # occur in your account. Learn more about
        # [webhooks](https://imagekit.io/docs/webhooks).
        sig do
          params(
            id: String,
            created_at: Time,
            enabled: T::Boolean,
            endpoint: String,
            events: T::Array[Imagekitio::Accounts::WebhookEventType::OrSymbol],
            secret: String,
            updated_at: Time
          ).returns(T.attached_class)
        end
        def self.new(
          # Unique identifier for a webhook.
          id:,
          # ISO 8601 timestamp of when the webhook was created.
          created_at:,
          # Whether the webhook is enabled. When `false`, ImageKit doesn't send any events
          # to the `endpoint`.
          enabled:,
          # The URL where ImageKit sends webhook events as `POST` requests. Must use the
          # `http` or `https` protocol, and must be unique across all webhooks for your
          # account.
          endpoint:,
          # The event types this webhook is subscribed to. ImageKit sends a request to the
          # `endpoint` only for these events.
          events:,
          # Signing secret generated by ImageKit, used to verify that webhook requests come
          # from ImageKit. Starts with `whsec_`. This value can't be set or changed through
          # the API. Learn more about
          # [verifying webhook signatures](https://imagekit.io/docs/webhooks#verify-webhook-signature).
          secret:,
          # ISO 8601 timestamp of when the webhook was last updated.
          updated_at:
        )
        end

        sig do
          override.returns(
            {
              id: String,
              created_at: Time,
              enabled: T::Boolean,
              endpoint: String,
              events:
                T::Array[Imagekitio::Accounts::WebhookEventType::TaggedSymbol],
              secret: String,
              updated_at: Time
            }
          )
        end
        def to_hash
        end
      end
    end
  end
end
