# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "imagekit/version"
require_relative "imagekit/internal/util"
require_relative "imagekit/internal/type/converter"
require_relative "imagekit/internal/type/unknown"
require_relative "imagekit/internal/type/boolean"
require_relative "imagekit/internal/type/file_input"
require_relative "imagekit/internal/type/enum"
require_relative "imagekit/internal/type/union"
require_relative "imagekit/internal/type/array_of"
require_relative "imagekit/internal/type/hash_of"
require_relative "imagekit/internal/type/base_model"
require_relative "imagekit/internal/type/base_page"
require_relative "imagekit/internal/type/request_parameters"
require_relative "imagekit/internal"
require_relative "imagekit/request_options"
require_relative "imagekit/file_part"
require_relative "imagekit/errors"
require_relative "imagekit/internal/transport/base_client"
require_relative "imagekit/internal/transport/pooled_net_requester"
require_relative "imagekit/client"
require_relative "imagekit/models/account_get_usage_params"
require_relative "imagekit/models/account_get_usage_response"
require_relative "imagekit/models/bulk_job_copy_folder_params"
require_relative "imagekit/models/bulk_job_copy_folder_response"
require_relative "imagekit/models/bulk_job_move_folder_params"
require_relative "imagekit/models/bulk_job_move_folder_response"
require_relative "imagekit/models/bulk_job_retrieve_status_params"
require_relative "imagekit/models/bulk_job_retrieve_status_response"
require_relative "imagekit/models/custom_metadata_field_create_params"
require_relative "imagekit/models/custom_metadata_field_create_response"
require_relative "imagekit/models/custom_metadata_field_delete_params"
require_relative "imagekit/models/custom_metadata_field_delete_response"
require_relative "imagekit/models/custom_metadata_field_list_params"
require_relative "imagekit/models/custom_metadata_field_list_response"
require_relative "imagekit/models/custom_metadata_field_update_params"
require_relative "imagekit/models/custom_metadata_field_update_response"
require_relative "imagekit/models/exif_details"
require_relative "imagekit/models/exif_image"
require_relative "imagekit/models/file_add_tags_params"
require_relative "imagekit/models/file_add_tags_response"
require_relative "imagekit/models/file_copy_params"
require_relative "imagekit/models/file_copy_response"
require_relative "imagekit/models/file_delete_params"
require_relative "imagekit/models/file_list_params"
require_relative "imagekit/models/file_list_response"
require_relative "imagekit/models/file_move_params"
require_relative "imagekit/models/file_move_response"
require_relative "imagekit/models/file_remove_ai_tags_params"
require_relative "imagekit/models/file_remove_ai_tags_response"
require_relative "imagekit/models/file_remove_tags_params"
require_relative "imagekit/models/file_remove_tags_response"
require_relative "imagekit/models/file_rename_params"
require_relative "imagekit/models/file_rename_response"
require_relative "imagekit/models/files/batch_delete_params"
require_relative "imagekit/models/files/batch_delete_response"
require_relative "imagekit/models/files/detail_retrieve_params"
require_relative "imagekit/models/files/detail_retrieve_response"
require_relative "imagekit/models/files/detail_update_params"
require_relative "imagekit/models/files/detail_update_response"
require_relative "imagekit/models/files/metadata_from_url_params"
require_relative "imagekit/models/files/metadata_from_url_response"
require_relative "imagekit/models/files/metadata_retrieve_params"
require_relative "imagekit/models/files/metadata_retrieve_response"
require_relative "imagekit/models/files/purge_execute_params"
require_relative "imagekit/models/files/purge_execute_response"
require_relative "imagekit/models/files/purge_status_params"
require_relative "imagekit/models/files/purge_status_response"
require_relative "imagekit/models/files/version_delete_params"
require_relative "imagekit/models/files/version_delete_response"
require_relative "imagekit/models/files/version_list_params"
require_relative "imagekit/models/files/version_list_response"
require_relative "imagekit/models/files/version_restore_params"
require_relative "imagekit/models/files/version_restore_response"
require_relative "imagekit/models/files/version_retrieve_params"
require_relative "imagekit/models/files/version_retrieve_response"
require_relative "imagekit/models/file_upload_v1_params"
require_relative "imagekit/models/file_upload_v1_response"
require_relative "imagekit/models/file_upload_v2_params"
require_relative "imagekit/models/file_upload_v2_response"
require_relative "imagekit/models/folder_create_params"
require_relative "imagekit/models/folder_create_response"
require_relative "imagekit/models/folder_delete_params"
require_relative "imagekit/models/folder_delete_response"
require_relative "imagekit/models/gps"
require_relative "imagekit/models/interoperability"
require_relative "imagekit/models/thumbnail"
require_relative "imagekit/models"
require_relative "imagekit/resources/accounts"
require_relative "imagekit/resources/bulk_jobs"
require_relative "imagekit/resources/custom_metadata_fields"
require_relative "imagekit/resources/files"
require_relative "imagekit/resources/files/batch"
require_relative "imagekit/resources/files/details"
require_relative "imagekit/resources/files/metadata"
require_relative "imagekit/resources/files/purge"
require_relative "imagekit/resources/files/versions"
require_relative "imagekit/resources/folder"
