module Imagekit
  module Resources
    class Accounts
      class Origins
        def create: (
          origin: Imagekit::Models::Accounts::origin,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_create_response

        def update: (
          String id,
          origin: Imagekit::Models::Accounts::origin,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_update_response

        def list: (
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_list_response

        def delete: (String id, ?request_options: Imagekit::request_opts) -> nil

        def get: (
          String id,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_get_response

        def initialize: (client: Imagekit::Client) -> void
      end
    end
  end
end
