module Imagekit
  module Resources
    class Accounts
      class Origins
        def create: (
          access_key: String,
          bucket: String,
          name: String,
          secret_key: String,
          type: Imagekit::Models::Accounts::OriginCreateParams::type_,
          endpoint: String,
          base_url: String,
          client_email: String,
          private_key: String,
          account_name: String,
          container: String,
          sas_token: String,
          client_id: String,
          client_secret: String,
          password: String,
          username: String,
          ?base_url_for_canonical_header: String,
          ?include_canonical_header: bool,
          ?prefix: String,
          ?s3_force_path_style: bool,
          ?forward_host_header_to_origin: bool,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_create_response

        def update: (
          String id,
          access_key: String,
          bucket: String,
          name: String,
          secret_key: String,
          type: Imagekit::Models::Accounts::OriginUpdateParams::type_,
          endpoint: String,
          base_url: String,
          client_email: String,
          private_key: String,
          account_name: String,
          container: String,
          sas_token: String,
          client_id: String,
          client_secret: String,
          password: String,
          username: String,
          ?base_url_for_canonical_header: String,
          ?include_canonical_header: bool,
          ?prefix: String,
          ?s3_force_path_style: bool,
          ?forward_host_header_to_origin: bool,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_update_response

        def list: (
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_list_response

        def delete: (String id, ?request_options: Imagekit::request_opts) -> nil

        def get: (
          String id,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Accounts::origin_get_response

        def initialize: (client: Imagekit::Client) -> void
      end
    end
  end
end
