module Imagekit
  module Resources
    class Files
      class Details
        def retrieve: (
          String file_id,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Files::DetailRetrieveResponse

        def update: (
          String file_id,
          ?custom_coordinates: String?,
          ?custom_metadata: top,
          ?extensions: ::Array[Imagekit::Models::Files::DetailUpdateParams::extension],
          ?remove_ai_tags: Imagekit::Models::Files::DetailUpdateParams::remove_ai_tags,
          ?tags: ::Array[String]?,
          ?webhook_url: String,
          ?publish: Imagekit::Files::DetailUpdateParams::Publish,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Files::DetailUpdateResponse

        def initialize: (client: Imagekit::Client) -> void
      end
    end
  end
end
