module Imagekit
  module Resources
    class Files
      class Purge
        def execute: (
          url: String,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Files::PurgeExecuteResponse

        def status: (
          String request_id,
          ?request_options: Imagekit::request_opts
        ) -> Imagekit::Models::Files::PurgeStatusResponse

        def initialize: (client: Imagekit::Client) -> void
      end
    end
  end
end
