module Imagekit
  module Models
    module Accounts
      type origin_update_params =
        { body: Imagekit::Accounts::OriginUpdateParams::Body }
        & Imagekit::Internal::Type::request_parameters

      class OriginUpdateParams < Imagekit::Internal::Type::BaseModel
        extend Imagekit::Internal::Type::RequestParameters::Converter
        include Imagekit::Internal::Type::RequestParameters

        attr_accessor body: Imagekit::Accounts::OriginUpdateParams::Body

        def initialize: (
          body: Imagekit::Accounts::OriginUpdateParams::Body,
          ?request_options: Imagekit::request_opts
        ) -> void

        def to_hash: -> {
          body: Imagekit::Accounts::OriginUpdateParams::Body,
          request_options: Imagekit::RequestOptions
        }

        type body = {  }

        class Body < Imagekit::Internal::Type::BaseModel
          def to_hash: -> {  }
        end
      end
    end
  end
end
