module Imagekit
  module Models
    module Accounts
      type origin_list_response = ::Array[Imagekit::Models::Accounts::origin]

      OriginListResponse: Imagekit::Internal::Type::Converter
    end
  end
end
