module Imagekit
  module Models
    module Accounts
      type origin_update_params =
        { origin_request: Imagekit::Models::Accounts::origin_request }
        & Imagekit::Internal::Type::request_parameters

      class OriginUpdateParams < Imagekit::Internal::Type::BaseModel
        extend Imagekit::Internal::Type::RequestParameters::Converter
        include Imagekit::Internal::Type::RequestParameters

        def origin_request: -> Imagekit::Models::Accounts::origin_request

        def origin_request=: (
          Imagekit::Models::Accounts::origin_request _
        ) -> Imagekit::Models::Accounts::origin_request

        def initialize: (
          origin_request: Imagekit::Models::Accounts::origin_request,
          ?request_options: Imagekit::request_opts
        ) -> void

        def to_hash: -> {
          origin_request: Imagekit::Models::Accounts::origin_request,
          request_options: Imagekit::RequestOptions
        }
      end
    end
  end
end
