module Imagekit
  module Models
    module Accounts
      type url_endpoint_response =
        {
          id: String,
          description: String,
          origins: ::Array[String],
          url_prefix: String,
          url_rewriter: Imagekit::Models::Accounts::URLEndpointResponse::url_rewriter
        }

      class URLEndpointResponse < Imagekit::Internal::Type::BaseModel
        attr_accessor description: String

        attr_accessor origins: ::Array[String]

        attr_accessor url_prefix: String

        attr_reader url_rewriter: Imagekit::Models::Accounts::URLEndpointResponse::url_rewriter?

        def url_rewriter=: (
          Imagekit::Models::Accounts::URLEndpointResponse::url_rewriter
        ) -> Imagekit::Models::Accounts::URLEndpointResponse::url_rewriter

        attr_accessor id: String

        def initialize: (
          id: String,
          description: String,
          origins: ::Array[String],
          url_prefix: String,
          ?url_rewriter: Imagekit::Models::Accounts::URLEndpointResponse::url_rewriter
        ) -> void

        def to_hash: -> {
          id: String,
          description: String,
          origins: ::Array[String],
          url_prefix: String,
          url_rewriter: Imagekit::Models::Accounts::URLEndpointResponse::url_rewriter
        }

        type url_rewriter =
          Imagekit::Accounts::URLEndpointResponse::URLRewriter::Cloudinary
          | Imagekit::Accounts::URLEndpointResponse::URLRewriter::Imgix
          | Imagekit::Accounts::URLEndpointResponse::URLRewriter::Akamai

        module URLRewriter
          extend Imagekit::Internal::Type::Union

          type cloudinary =
            { preserve_asset_delivery_types: bool, type: :CLOUDINARY }

          class Cloudinary < Imagekit::Internal::Type::BaseModel
            attr_accessor preserve_asset_delivery_types: bool

            attr_accessor type: :CLOUDINARY

            def initialize: (
              preserve_asset_delivery_types: bool,
              ?type: :CLOUDINARY
            ) -> void

            def to_hash: -> {
              preserve_asset_delivery_types: bool,
              type: :CLOUDINARY
            }
          end

          type imgix = { type: :IMGIX }

          class Imgix < Imagekit::Internal::Type::BaseModel
            attr_accessor type: :IMGIX

            def initialize: (?type: :IMGIX) -> void

            def to_hash: -> { type: :IMGIX }
          end

          type akamai = { type: :AKAMAI }

          class Akamai < Imagekit::Internal::Type::BaseModel
            attr_accessor type: :AKAMAI

            def initialize: (?type: :AKAMAI) -> void

            def to_hash: -> { type: :AKAMAI }
          end

          def self?.variants: -> ::Array[Imagekit::Models::Accounts::URLEndpointResponse::url_rewriter]
        end
      end
    end
  end
end
