module Imagekit
  module Models
    module Accounts
      type url_endpoint_list_response =
        ::Array[Imagekit::Accounts::URLEndpointResponse]

      URLEndpointListResponse: Imagekit::Internal::Type::Converter
    end
  end
end
