# frozen_string_literal: true

module Imagekitio
  module Resources
    class Accounts
      class Origins
        # **Note:** This API is currently in beta.
        # Creates a new origin and returns the origin object.
        #
        # @overload create(origin_request:, request_options: {})
        #
        # @param origin_request [Imagekitio::Accounts::OriginRequest] Schema for origin request resources.
        #
        # @param request_options [Imagekitio::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekitio::Models::Accounts::OriginResponse::S3, Imagekitio::Models::Accounts::OriginResponse::S3Compatible, Imagekitio::Models::Accounts::OriginResponse::CloudinaryBackup, Imagekitio::Models::Accounts::OriginResponse::WebFolder, Imagekitio::Models::Accounts::OriginResponse::WebProxy, Imagekitio::Models::Accounts::OriginResponse::Gcs, Imagekitio::Models::Accounts::OriginResponse::AzureBlob, Imagekitio::Models::Accounts::OriginResponse::AkeneoPim]
        #
        # @see Imagekitio::Models::Accounts::OriginCreateParams
        def create(params)
          parsed, options = Imagekitio::Accounts::OriginCreateParams.dump_request(params)
          case parsed
          in {origin_request: Hash => union, **rest}
            parsed = {**rest, **union}
          else
          end
          @client.request(
            method: :post,
            path: "v1/accounts/origins",
            body: parsed,
            model: Imagekitio::Accounts::OriginResponse,
            options: options
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekitio::Models::Accounts::OriginUpdateParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Updates the origin identified by `id` and returns the updated origin object.
        #
        # @overload update(id, origin_request:, request_options: {})
        #
        # @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
        #
        # @param origin_request [Imagekitio::Accounts::OriginRequest] Schema for origin request resources.
        #
        # @param request_options [Imagekitio::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekitio::Models::Accounts::OriginResponse::S3, Imagekitio::Models::Accounts::OriginResponse::S3Compatible, Imagekitio::Models::Accounts::OriginResponse::CloudinaryBackup, Imagekitio::Models::Accounts::OriginResponse::WebFolder, Imagekitio::Models::Accounts::OriginResponse::WebProxy, Imagekitio::Models::Accounts::OriginResponse::Gcs, Imagekitio::Models::Accounts::OriginResponse::AzureBlob, Imagekitio::Models::Accounts::OriginResponse::AkeneoPim]
        #
        # @see Imagekitio::Models::Accounts::OriginUpdateParams
        def update(id, params)
          parsed, options = Imagekitio::Accounts::OriginUpdateParams.dump_request(params)
          case parsed
          in {origin_request: Hash => union, **rest}
            parsed = {**rest, **union}
          else
          end
          @client.request(
            method: :put,
            path: ["v1/accounts/origins/%1$s", id],
            body: parsed,
            model: Imagekitio::Accounts::OriginResponse,
            options: options
          )
        end

        # **Note:** This API is currently in beta.
        # Returns an array of all configured origins for the current account.
        #
        # @overload list(request_options: {})
        #
        # @param request_options [Imagekitio::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Array<Imagekitio::Models::Accounts::OriginResponse::S3, Imagekitio::Models::Accounts::OriginResponse::S3Compatible, Imagekitio::Models::Accounts::OriginResponse::CloudinaryBackup, Imagekitio::Models::Accounts::OriginResponse::WebFolder, Imagekitio::Models::Accounts::OriginResponse::WebProxy, Imagekitio::Models::Accounts::OriginResponse::Gcs, Imagekitio::Models::Accounts::OriginResponse::AzureBlob, Imagekitio::Models::Accounts::OriginResponse::AkeneoPim>]
        #
        # @see Imagekitio::Models::Accounts::OriginListParams
        def list(params = {})
          @client.request(
            method: :get,
            path: "v1/accounts/origins",
            model: Imagekitio::Internal::Type::ArrayOf[union: Imagekitio::Accounts::OriginResponse],
            options: params[:request_options]
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekitio::Models::Accounts::OriginDeleteParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Permanently removes the origin identified by `id`. If the origin is in use by
        # any URL‑endpoints, the API will return an error.
        #
        # @overload delete(id, request_options: {})
        #
        # @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
        #
        # @param request_options [Imagekitio::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [nil]
        #
        # @see Imagekitio::Models::Accounts::OriginDeleteParams
        def delete(id, params = {})
          @client.request(
            method: :delete,
            path: ["v1/accounts/origins/%1$s", id],
            model: NilClass,
            options: params[:request_options]
          )
        end

        # Some parameter documentations has been truncated, see
        # {Imagekitio::Models::Accounts::OriginGetParams} for more details.
        #
        # **Note:** This API is currently in beta.
        # Retrieves the origin identified by `id`.
        #
        # @overload get(id, request_options: {})
        #
        # @param id [String] Unique identifier for the origin. This is generated by ImageKit when you create
        #
        # @param request_options [Imagekitio::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [Imagekitio::Models::Accounts::OriginResponse::S3, Imagekitio::Models::Accounts::OriginResponse::S3Compatible, Imagekitio::Models::Accounts::OriginResponse::CloudinaryBackup, Imagekitio::Models::Accounts::OriginResponse::WebFolder, Imagekitio::Models::Accounts::OriginResponse::WebProxy, Imagekitio::Models::Accounts::OriginResponse::Gcs, Imagekitio::Models::Accounts::OriginResponse::AzureBlob, Imagekitio::Models::Accounts::OriginResponse::AkeneoPim]
        #
        # @see Imagekitio::Models::Accounts::OriginGetParams
        def get(id, params = {})
          @client.request(
            method: :get,
            path: ["v1/accounts/origins/%1$s", id],
            model: Imagekitio::Accounts::OriginResponse,
            options: params[:request_options]
          )
        end

        # @api private
        #
        # @param client [Imagekitio::Client]
        def initialize(client:)
          @client = client
        end
      end
    end
  end
end
