module Imagekit
  module Accounts = Imagekit::Models::Accounts

  class AssetListParams = Imagekit::Models::AssetListParams

  class BaseOverlay = Imagekit::Models::BaseOverlay

  class BaseWebhookEvent = Imagekit::Models::BaseWebhookEvent

  module Beta = Imagekit::Models::Beta

  module Cache = Imagekit::Models::Cache

  class CustomMetadataField = Imagekit::Models::CustomMetadataField

  class CustomMetadataFieldCreateParams = Imagekit::Models::CustomMetadataFieldCreateParams

  class CustomMetadataFieldDeleteParams = Imagekit::Models::CustomMetadataFieldDeleteParams

  class CustomMetadataFieldListParams = Imagekit::Models::CustomMetadataFieldListParams

  class CustomMetadataFieldUpdateParams = Imagekit::Models::CustomMetadataFieldUpdateParams

  type extension_item = Imagekit::Models::extension_item

  Extensions: Imagekit::Internal::Type::Converter

  class File = Imagekit::Models::File

  class FileCopyParams = Imagekit::Models::FileCopyParams

  class FileDeleteParams = Imagekit::Models::FileDeleteParams

  class FileGetParams = Imagekit::Models::FileGetParams

  class FileMoveParams = Imagekit::Models::FileMoveParams

  class FileRenameParams = Imagekit::Models::FileRenameParams

  module Files = Imagekit::Models::Files

  class FileUpdateParams = Imagekit::Models::FileUpdateParams

  class FileUploadParams = Imagekit::Models::FileUploadParams

  class Folder = Imagekit::Models::Folder

  class FolderCopyParams = Imagekit::Models::FolderCopyParams

  class FolderCreateParams = Imagekit::Models::FolderCreateParams

  class FolderDeleteParams = Imagekit::Models::FolderDeleteParams

  class FolderMoveParams = Imagekit::Models::FolderMoveParams

  class FolderRenameParams = Imagekit::Models::FolderRenameParams

  module Folders = Imagekit::Models::Folders

  class ImageOverlay = Imagekit::Models::ImageOverlay

  class Metadata = Imagekit::Models::Metadata

  module Overlay = Imagekit::Models::Overlay

  class OverlayPosition = Imagekit::Models::OverlayPosition

  class OverlayTiming = Imagekit::Models::OverlayTiming

  class SolidColorOverlay = Imagekit::Models::SolidColorOverlay

  class SolidColorOverlayTransformation = Imagekit::Models::SolidColorOverlayTransformation

  class SrcOptions = Imagekit::Models::SrcOptions

  module StreamingResolution = Imagekit::Models::StreamingResolution

  class SubtitleOverlay = Imagekit::Models::SubtitleOverlay

  class SubtitleOverlayTransformation = Imagekit::Models::SubtitleOverlayTransformation

  class TextOverlay = Imagekit::Models::TextOverlay

  class TextOverlayTransformation = Imagekit::Models::TextOverlayTransformation

  class Transformation = Imagekit::Models::Transformation

  module TransformationPosition = Imagekit::Models::TransformationPosition

  module UnsafeUnwrapWebhookEvent = Imagekit::Models::UnsafeUnwrapWebhookEvent

  module UnwrapWebhookEvent = Imagekit::Models::UnwrapWebhookEvent

  class UploadPostTransformErrorEvent = Imagekit::Models::UploadPostTransformErrorEvent

  class UploadPostTransformSuccessEvent = Imagekit::Models::UploadPostTransformSuccessEvent

  class UploadPreTransformErrorEvent = Imagekit::Models::UploadPreTransformErrorEvent

  class UploadPreTransformSuccessEvent = Imagekit::Models::UploadPreTransformSuccessEvent

  class VideoOverlay = Imagekit::Models::VideoOverlay

  class VideoTransformationAcceptedEvent = Imagekit::Models::VideoTransformationAcceptedEvent

  class VideoTransformationErrorEvent = Imagekit::Models::VideoTransformationErrorEvent

  class VideoTransformationReadyEvent = Imagekit::Models::VideoTransformationReadyEvent

  class WebhookUnsafeUnwrapParams = Imagekit::Models::WebhookUnsafeUnwrapParams

  class WebhookUnwrapParams = Imagekit::Models::WebhookUnwrapParams
end
