module Imagekitio
  module Internal
    module Type
      class HashOf[Elem]
        include Imagekitio::Internal::Type::Converter
        include Imagekitio::Internal::Util::SorbetRuntimeSupport

        def self.[]: (
          ::Hash[Symbol, top]
          | ^-> Imagekitio::Internal::Type::Converter::input
          | Imagekitio::Internal::Type::Converter::input type_info,
          ?::Hash[Symbol, top] spec
        ) -> instance

        def ===: (top other) -> bool

        def ==: (top other) -> bool

        def hash: -> Integer

        def coerce: (
          ::Hash[top, top] | top value,
          state: Imagekitio::Internal::Type::Converter::coerce_state
        ) -> (::Hash[Symbol, top] | top)

        def dump: (
          ::Hash[top, top] | top value,
          state: Imagekitio::Internal::Type::Converter::dump_state
        ) -> (::Hash[Symbol, top] | top)

        def to_sorbet_type: -> top

        def item_type: -> Elem

        def nilable?: -> bool

        def initialize: (
          ::Hash[Symbol, top]
          | ^-> Imagekitio::Internal::Type::Converter::input
          | Imagekitio::Internal::Type::Converter::input type_info,
          ?::Hash[Symbol, top] spec
        ) -> void

        def inspect: (?depth: Integer) -> String
      end
    end
  end
end
