module Imagekitio
  module Resources
    class Accounts
      class Usage
        def get: (
          end_date: Date,
          start_date: Date,
          ?request_options: Imagekitio::request_opts
        ) -> Imagekitio::Models::Accounts::UsageGetResponse

        def initialize: (client: Imagekitio::Client) -> void
      end
    end
  end
end
